/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class cpputilsJNI {
  public final static native int setCanvasHwnd_w(Object jarg1, long jarg2);
  public final static native int stub_w(Object jarg1, long jarg2);
  public final static native int getGLHWND_w(long jarg1);
  public final static native void array_set(int[] jarg1);
  public final static native int[] array_get();
  public final static native void populate(int[] jarg1);
  public final static native boolean booleanArray_getitem(long jarg1, int jarg2);
  public final static native int intArray_getitem(long jarg1, int jarg2);
}
