/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class cpputils {
  public static int setCanvasHwnd_w(Object canvas, SWIGTYPE_p_GLFWwindow window) {
    return cpputilsJNI.setCanvasHwnd_w(canvas, SWIGTYPE_p_GLFWwindow.getCPtr(window));
  }

  public static int stub_w(Object canvas, SWIGTYPE_p_GLFWwindow window) {
    return cpputilsJNI.stub_w(canvas, SWIGTYPE_p_GLFWwindow.getCPtr(window));
  }

  public static int getGLHWND_w(SWIGTYPE_p_GLFWwindow window) {
    return cpputilsJNI.getGLHWND_w(SWIGTYPE_p_GLFWwindow.getCPtr(window));
  }

  public static void setArray(int[] value) {
    cpputilsJNI.array_set(value);
  }

  public static int[] getArray() {
    return cpputilsJNI.array_get();
  }

  public static void populate(int[] x) {
    cpputilsJNI.populate(x);
  }

  public static boolean booleanArray_getitem(SWIGTYPE_p_bool x, int index) {
    return cpputilsJNI.booleanArray_getitem(SWIGTYPE_p_bool.getCPtr(x), index);
  }

  public static int intArray_getitem(SWIGTYPE_p_int x, int index) {
    return cpputilsJNI.intArray_getitem(SWIGTYPE_p_int.getCPtr(x), index);
  }

}
