/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class example {
  public static void setArray(int[] value) {
    exampleJNI.array_set(value);
  }

  public static int[] getArray() {
    return exampleJNI.array_get();
  }

  public static void populate(int[] x) {
    exampleJNI.populate(x);
  }

}
