/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class exampleJNI {
  public final static native void array_set(int[] jarg1);
  public final static native int[] array_get();
  public final static native void populate(int[] jarg1);
}
