/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImColor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImColor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImColor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImColor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(ImVec4 value) {
    jimguiJNI.ImColor_Value_set(swigCPtr, this, ImVec4.getCPtr(value), value);
  }

  public ImVec4 getValue() {
    long cPtr = jimguiJNI.ImColor_Value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec4(cPtr, false);
  }

  public ImColor() {
    this(jimguiJNI.new_ImColor__SWIG_0(), true);
  }

  public ImColor(int r, int g, int b, int a) {
    this(jimguiJNI.new_ImColor__SWIG_1(r, g, b, a), true);
  }

  public ImColor(int r, int g, int b) {
    this(jimguiJNI.new_ImColor__SWIG_2(r, g, b), true);
  }

  public ImColor(long rgba) {
    this(jimguiJNI.new_ImColor__SWIG_3(rgba), true);
  }

  public ImColor(float r, float g, float b, float a) {
    this(jimguiJNI.new_ImColor__SWIG_4(r, g, b, a), true);
  }

  public ImColor(float r, float g, float b) {
    this(jimguiJNI.new_ImColor__SWIG_5(r, g, b), true);
  }

  public ImColor(ImVec4 col) {
    this(jimguiJNI.new_ImColor__SWIG_6(ImVec4.getCPtr(col), col), true);
  }

  public void SetHSV(float h, float s, float v, float a) {
    jimguiJNI.ImColor_SetHSV__SWIG_0(swigCPtr, this, h, s, v, a);
  }

  public void SetHSV(float h, float s, float v) {
    jimguiJNI.ImColor_SetHSV__SWIG_1(swigCPtr, this, h, s, v);
  }

  public static ImColor HSV(float h, float s, float v, float a) {
    return new ImColor(jimguiJNI.ImColor_HSV__SWIG_0(h, s, v, a), true);
  }

  public static ImColor HSV(float h, float s, float v) {
    return new ImColor(jimguiJNI.ImColor_HSV__SWIG_1(h, s, v), true);
  }

}
