/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImDrawCornerFlags_ {
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_TopLeft = new ImDrawCornerFlags_("ImDrawCornerFlags_TopLeft", jimguiJNI.ImDrawCornerFlags_TopLeft_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_TopRight = new ImDrawCornerFlags_("ImDrawCornerFlags_TopRight", jimguiJNI.ImDrawCornerFlags_TopRight_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_BotLeft = new ImDrawCornerFlags_("ImDrawCornerFlags_BotLeft", jimguiJNI.ImDrawCornerFlags_BotLeft_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_BotRight = new ImDrawCornerFlags_("ImDrawCornerFlags_BotRight", jimguiJNI.ImDrawCornerFlags_BotRight_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_Top = new ImDrawCornerFlags_("ImDrawCornerFlags_Top", jimguiJNI.ImDrawCornerFlags_Top_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_Bot = new ImDrawCornerFlags_("ImDrawCornerFlags_Bot", jimguiJNI.ImDrawCornerFlags_Bot_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_Left = new ImDrawCornerFlags_("ImDrawCornerFlags_Left", jimguiJNI.ImDrawCornerFlags_Left_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_Right = new ImDrawCornerFlags_("ImDrawCornerFlags_Right", jimguiJNI.ImDrawCornerFlags_Right_get());
  public final static ImDrawCornerFlags_ ImDrawCornerFlags_All = new ImDrawCornerFlags_("ImDrawCornerFlags_All", jimguiJNI.ImDrawCornerFlags_All_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImDrawCornerFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImDrawCornerFlags_.class + " with value " + swigValue);
  }

  private ImDrawCornerFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImDrawCornerFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImDrawCornerFlags_(String swigName, ImDrawCornerFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImDrawCornerFlags_[] swigValues = { ImDrawCornerFlags_TopLeft, ImDrawCornerFlags_TopRight, ImDrawCornerFlags_BotLeft, ImDrawCornerFlags_BotRight, ImDrawCornerFlags_Top, ImDrawCornerFlags_Bot, ImDrawCornerFlags_Left, ImDrawCornerFlags_Right, ImDrawCornerFlags_All };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

