/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImDrawCmd {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImDrawCmd(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImDrawCmd obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImDrawCmd(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setElemCount(long value) {
    jimguiJNI.ImDrawCmd_ElemCount_set(swigCPtr, this, value);
  }

  public long getElemCount() {
    return jimguiJNI.ImDrawCmd_ElemCount_get(swigCPtr, this);
  }

  public void setClipRect(ImVec4 value) {
    jimguiJNI.ImDrawCmd_ClipRect_set(swigCPtr, this, ImVec4.getCPtr(value), value);
  }

  public ImVec4 getClipRect() {
    long cPtr = jimguiJNI.ImDrawCmd_ClipRect_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec4(cPtr, false);
  }

  public void setTextureId(SWIGTYPE_p_void value) {
    jimguiJNI.ImDrawCmd_TextureId_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getTextureId() {
    long cPtr = jimguiJNI.ImDrawCmd_TextureId_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setUserCallback(SWIGTYPE_p_f_p_q_const__ImDrawList_p_q_const__ImDrawCmd__void value) {
    jimguiJNI.ImDrawCmd_UserCallback_set(swigCPtr, this, SWIGTYPE_p_f_p_q_const__ImDrawList_p_q_const__ImDrawCmd__void.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_q_const__ImDrawList_p_q_const__ImDrawCmd__void getUserCallback() {
    long cPtr = jimguiJNI.ImDrawCmd_UserCallback_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_q_const__ImDrawList_p_q_const__ImDrawCmd__void(cPtr, false);
  }

  public void setUserCallbackData(SWIGTYPE_p_void value) {
    jimguiJNI.ImDrawCmd_UserCallbackData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserCallbackData() {
    long cPtr = jimguiJNI.ImDrawCmd_UserCallbackData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ImDrawCmd() {
    this(jimguiJNI.new_ImDrawCmd(), true);
  }

}
