/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImDrawListFlags_ {
  public final static ImDrawListFlags_ ImDrawListFlags_AntiAliasedLines = new ImDrawListFlags_("ImDrawListFlags_AntiAliasedLines", jimguiJNI.ImDrawListFlags_AntiAliasedLines_get());
  public final static ImDrawListFlags_ ImDrawListFlags_AntiAliasedFill = new ImDrawListFlags_("ImDrawListFlags_AntiAliasedFill", jimguiJNI.ImDrawListFlags_AntiAliasedFill_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImDrawListFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImDrawListFlags_.class + " with value " + swigValue);
  }

  private ImDrawListFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImDrawListFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImDrawListFlags_(String swigName, ImDrawListFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImDrawListFlags_[] swigValues = { ImDrawListFlags_AntiAliasedLines, ImDrawListFlags_AntiAliasedFill };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

