/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImDrawData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImDrawData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImDrawData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImDrawData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValid(boolean value) {
    jimguiJNI.ImDrawData_Valid_set(swigCPtr, this, value);
  }

  public boolean getValid() {
    return jimguiJNI.ImDrawData_Valid_get(swigCPtr, this);
  }

  public void setCmdLists(SWIGTYPE_p_p_ImDrawList value) {
    jimguiJNI.ImDrawData_CmdLists_set(swigCPtr, this, SWIGTYPE_p_p_ImDrawList.getCPtr(value));
  }

  public SWIGTYPE_p_p_ImDrawList getCmdLists() {
    long cPtr = jimguiJNI.ImDrawData_CmdLists_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_ImDrawList(cPtr, false);
  }

  public void setCmdListsCount(int value) {
    jimguiJNI.ImDrawData_CmdListsCount_set(swigCPtr, this, value);
  }

  public int getCmdListsCount() {
    return jimguiJNI.ImDrawData_CmdListsCount_get(swigCPtr, this);
  }

  public void setTotalIdxCount(int value) {
    jimguiJNI.ImDrawData_TotalIdxCount_set(swigCPtr, this, value);
  }

  public int getTotalIdxCount() {
    return jimguiJNI.ImDrawData_TotalIdxCount_get(swigCPtr, this);
  }

  public void setTotalVtxCount(int value) {
    jimguiJNI.ImDrawData_TotalVtxCount_set(swigCPtr, this, value);
  }

  public int getTotalVtxCount() {
    return jimguiJNI.ImDrawData_TotalVtxCount_get(swigCPtr, this);
  }

  public void setDisplayPos(ImVec2 value) {
    jimguiJNI.ImDrawData_DisplayPos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplayPos() {
    long cPtr = jimguiJNI.ImDrawData_DisplayPos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDisplaySize(ImVec2 value) {
    jimguiJNI.ImDrawData_DisplaySize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplaySize() {
    long cPtr = jimguiJNI.ImDrawData_DisplaySize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public ImDrawData() {
    this(jimguiJNI.new_ImDrawData(), true);
  }

  public void Clear() {
    jimguiJNI.ImDrawData_Clear(swigCPtr, this);
  }

  public void DeIndexAllBuffers() {
    jimguiJNI.ImDrawData_DeIndexAllBuffers(swigCPtr, this);
  }

  public void ScaleClipRects(ImVec2 sc) {
    jimguiJNI.ImDrawData_ScaleClipRects(swigCPtr, this, ImVec2.getCPtr(sc), sc);
  }

}
