/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImDrawList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImDrawList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImDrawList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImDrawList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCmdBuffer(SWIGTYPE_p_ImVectorT_ImDrawCmd_t value) {
    jimguiJNI.ImDrawList_CmdBuffer_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImDrawCmd_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImDrawCmd_t getCmdBuffer() {
    long cPtr = jimguiJNI.ImDrawList_CmdBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImDrawCmd_t(cPtr, false);
  }

  public void setIdxBuffer(SWIGTYPE_p_ImVectorT_unsigned_short_t value) {
    jimguiJNI.ImDrawList_IdxBuffer_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_unsigned_short_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_unsigned_short_t getIdxBuffer() {
    long cPtr = jimguiJNI.ImDrawList_IdxBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_unsigned_short_t(cPtr, false);
  }

  public void setVtxBuffer(SWIGTYPE_p_ImVectorT_ImDrawVert_t value) {
    jimguiJNI.ImDrawList_VtxBuffer_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImDrawVert_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImDrawVert_t getVtxBuffer() {
    long cPtr = jimguiJNI.ImDrawList_VtxBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImDrawVert_t(cPtr, false);
  }

  public void setFlags(int value) {
    jimguiJNI.ImDrawList_Flags_set(swigCPtr, this, value);
  }

  public int getFlags() {
    return jimguiJNI.ImDrawList_Flags_get(swigCPtr, this);
  }

  public void set_Data(SWIGTYPE_p_ImDrawListSharedData value) {
    jimguiJNI.ImDrawList__Data_set(swigCPtr, this, SWIGTYPE_p_ImDrawListSharedData.getCPtr(value));
  }

  public SWIGTYPE_p_ImDrawListSharedData get_Data() {
    long cPtr = jimguiJNI.ImDrawList__Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImDrawListSharedData(cPtr, false);
  }

  public void set_OwnerName(String value) {
    jimguiJNI.ImDrawList__OwnerName_set(swigCPtr, this, value);
  }

  public String get_OwnerName() {
    return jimguiJNI.ImDrawList__OwnerName_get(swigCPtr, this);
  }

  public void set_VtxCurrentIdx(long value) {
    jimguiJNI.ImDrawList__VtxCurrentIdx_set(swigCPtr, this, value);
  }

  public long get_VtxCurrentIdx() {
    return jimguiJNI.ImDrawList__VtxCurrentIdx_get(swigCPtr, this);
  }

  public void set_VtxWritePtr(ImDrawVert value) {
    jimguiJNI.ImDrawList__VtxWritePtr_set(swigCPtr, this, ImDrawVert.getCPtr(value), value);
  }

  public ImDrawVert get_VtxWritePtr() {
    long cPtr = jimguiJNI.ImDrawList__VtxWritePtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawVert(cPtr, false);
  }

  public void set_IdxWritePtr(SWIGTYPE_p_unsigned_short value) {
    jimguiJNI.ImDrawList__IdxWritePtr_set(swigCPtr, this, SWIGTYPE_p_unsigned_short.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_short get_IdxWritePtr() {
    long cPtr = jimguiJNI.ImDrawList__IdxWritePtr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_short(cPtr, false);
  }

  public void set_ClipRectStack(SWIGTYPE_p_ImVectorT_ImVec4_t value) {
    jimguiJNI.ImDrawList__ClipRectStack_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImVec4_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImVec4_t get_ClipRectStack() {
    long cPtr = jimguiJNI.ImDrawList__ClipRectStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImVec4_t(cPtr, false);
  }

  public void set_TextureIdStack(SWIGTYPE_p_ImVectorT_void_p_t value) {
    jimguiJNI.ImDrawList__TextureIdStack_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_void_p_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_void_p_t get_TextureIdStack() {
    long cPtr = jimguiJNI.ImDrawList__TextureIdStack_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_void_p_t(cPtr, false);
  }

  public void set_Path(SWIGTYPE_p_ImVectorT_ImVec2_t value) {
    jimguiJNI.ImDrawList__Path_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImVec2_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImVec2_t get_Path() {
    long cPtr = jimguiJNI.ImDrawList__Path_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImVec2_t(cPtr, false);
  }

  public void set_ChannelsCurrent(int value) {
    jimguiJNI.ImDrawList__ChannelsCurrent_set(swigCPtr, this, value);
  }

  public int get_ChannelsCurrent() {
    return jimguiJNI.ImDrawList__ChannelsCurrent_get(swigCPtr, this);
  }

  public void set_ChannelsCount(int value) {
    jimguiJNI.ImDrawList__ChannelsCount_set(swigCPtr, this, value);
  }

  public int get_ChannelsCount() {
    return jimguiJNI.ImDrawList__ChannelsCount_get(swigCPtr, this);
  }

  public void set_Channels(SWIGTYPE_p_ImVectorT_ImDrawChannel_t value) {
    jimguiJNI.ImDrawList__Channels_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImDrawChannel_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImDrawChannel_t get_Channels() {
    long cPtr = jimguiJNI.ImDrawList__Channels_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImDrawChannel_t(cPtr, false);
  }

  public ImDrawList(SWIGTYPE_p_ImDrawListSharedData shared_data) {
    this(jimguiJNI.new_ImDrawList(SWIGTYPE_p_ImDrawListSharedData.getCPtr(shared_data)), true);
  }

  public void PushClipRect(ImVec2 clip_rect_min, ImVec2 clip_rect_max, boolean intersect_with_current_clip_rect) {
    jimguiJNI.ImDrawList_PushClipRect__SWIG_0(swigCPtr, this, ImVec2.getCPtr(clip_rect_min), clip_rect_min, ImVec2.getCPtr(clip_rect_max), clip_rect_max, intersect_with_current_clip_rect);
  }

  public void PushClipRect(ImVec2 clip_rect_min, ImVec2 clip_rect_max) {
    jimguiJNI.ImDrawList_PushClipRect__SWIG_1(swigCPtr, this, ImVec2.getCPtr(clip_rect_min), clip_rect_min, ImVec2.getCPtr(clip_rect_max), clip_rect_max);
  }

  public void PushClipRectFullScreen() {
    jimguiJNI.ImDrawList_PushClipRectFullScreen(swigCPtr, this);
  }

  public void PopClipRect() {
    jimguiJNI.ImDrawList_PopClipRect(swigCPtr, this);
  }

  public void PushTextureID(SWIGTYPE_p_void texture_id) {
    jimguiJNI.ImDrawList_PushTextureID(swigCPtr, this, SWIGTYPE_p_void.getCPtr(texture_id));
  }

  public void PopTextureID() {
    jimguiJNI.ImDrawList_PopTextureID(swigCPtr, this);
  }

  public ImVec2 GetClipRectMin() {
    return new ImVec2(jimguiJNI.ImDrawList_GetClipRectMin(swigCPtr, this), true);
  }

  public ImVec2 GetClipRectMax() {
    return new ImVec2(jimguiJNI.ImDrawList_GetClipRectMax(swigCPtr, this), true);
  }

  public void AddLine(ImVec2 a, ImVec2 b, long col, float thickness) {
    jimguiJNI.ImDrawList_AddLine__SWIG_0(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col, thickness);
  }

  public void AddLine(ImVec2 a, ImVec2 b, long col) {
    jimguiJNI.ImDrawList_AddLine__SWIG_1(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col);
  }

  public void AddRect(ImVec2 a, ImVec2 b, long col, float rounding, int rounding_corners_flags, float thickness) {
    jimguiJNI.ImDrawList_AddRect__SWIG_0(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col, rounding, rounding_corners_flags, thickness);
  }

  public void AddRect(ImVec2 a, ImVec2 b, long col, float rounding, int rounding_corners_flags) {
    jimguiJNI.ImDrawList_AddRect__SWIG_1(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col, rounding, rounding_corners_flags);
  }

  public void AddRect(ImVec2 a, ImVec2 b, long col, float rounding) {
    jimguiJNI.ImDrawList_AddRect__SWIG_2(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col, rounding);
  }

  public void AddRect(ImVec2 a, ImVec2 b, long col) {
    jimguiJNI.ImDrawList_AddRect__SWIG_3(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col);
  }

  public void AddRectFilled(ImVec2 a, ImVec2 b, long col, float rounding, int rounding_corners_flags) {
    jimguiJNI.ImDrawList_AddRectFilled__SWIG_0(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col, rounding, rounding_corners_flags);
  }

  public void AddRectFilled(ImVec2 a, ImVec2 b, long col, float rounding) {
    jimguiJNI.ImDrawList_AddRectFilled__SWIG_1(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col, rounding);
  }

  public void AddRectFilled(ImVec2 a, ImVec2 b, long col) {
    jimguiJNI.ImDrawList_AddRectFilled__SWIG_2(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col);
  }

  public void AddRectFilledMultiColor(ImVec2 a, ImVec2 b, long col_upr_left, long col_upr_right, long col_bot_right, long col_bot_left) {
    jimguiJNI.ImDrawList_AddRectFilledMultiColor(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col_upr_left, col_upr_right, col_bot_right, col_bot_left);
  }

  public void AddQuad(ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, long col, float thickness) {
    jimguiJNI.ImDrawList_AddQuad__SWIG_0(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, col, thickness);
  }

  public void AddQuad(ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, long col) {
    jimguiJNI.ImDrawList_AddQuad__SWIG_1(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, col);
  }

  public void AddQuadFilled(ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, long col) {
    jimguiJNI.ImDrawList_AddQuadFilled(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, col);
  }

  public void AddTriangle(ImVec2 a, ImVec2 b, ImVec2 c, long col, float thickness) {
    jimguiJNI.ImDrawList_AddTriangle__SWIG_0(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, col, thickness);
  }

  public void AddTriangle(ImVec2 a, ImVec2 b, ImVec2 c, long col) {
    jimguiJNI.ImDrawList_AddTriangle__SWIG_1(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, col);
  }

  public void AddTriangleFilled(ImVec2 a, ImVec2 b, ImVec2 c, long col) {
    jimguiJNI.ImDrawList_AddTriangleFilled(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, col);
  }

  public void AddCircle(ImVec2 centre, float radius, long col, int num_segments, float thickness) {
    jimguiJNI.ImDrawList_AddCircle__SWIG_0(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, col, num_segments, thickness);
  }

  public void AddCircle(ImVec2 centre, float radius, long col, int num_segments) {
    jimguiJNI.ImDrawList_AddCircle__SWIG_1(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, col, num_segments);
  }

  public void AddCircle(ImVec2 centre, float radius, long col) {
    jimguiJNI.ImDrawList_AddCircle__SWIG_2(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, col);
  }

  public void AddCircleFilled(ImVec2 centre, float radius, long col, int num_segments) {
    jimguiJNI.ImDrawList_AddCircleFilled__SWIG_0(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, col, num_segments);
  }

  public void AddCircleFilled(ImVec2 centre, float radius, long col) {
    jimguiJNI.ImDrawList_AddCircleFilled__SWIG_1(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, col);
  }

  public void AddText(ImVec2 pos, long col, String text_begin, String text_end) {
    jimguiJNI.ImDrawList_AddText__SWIG_0(swigCPtr, this, ImVec2.getCPtr(pos), pos, col, text_begin, text_end);
  }

  public void AddText(ImVec2 pos, long col, String text_begin) {
    jimguiJNI.ImDrawList_AddText__SWIG_1(swigCPtr, this, ImVec2.getCPtr(pos), pos, col, text_begin);
  }

  public void AddText(ImFont font, float font_size, ImVec2 pos, long col, String text_begin, String text_end, float wrap_width, ImVec4 cpu_fine_clip_rect) {
    jimguiJNI.ImDrawList_AddText__SWIG_2(swigCPtr, this, ImFont.getCPtr(font), font, font_size, ImVec2.getCPtr(pos), pos, col, text_begin, text_end, wrap_width, ImVec4.getCPtr(cpu_fine_clip_rect), cpu_fine_clip_rect);
  }

  public void AddText(ImFont font, float font_size, ImVec2 pos, long col, String text_begin, String text_end, float wrap_width) {
    jimguiJNI.ImDrawList_AddText__SWIG_3(swigCPtr, this, ImFont.getCPtr(font), font, font_size, ImVec2.getCPtr(pos), pos, col, text_begin, text_end, wrap_width);
  }

  public void AddText(ImFont font, float font_size, ImVec2 pos, long col, String text_begin, String text_end) {
    jimguiJNI.ImDrawList_AddText__SWIG_4(swigCPtr, this, ImFont.getCPtr(font), font, font_size, ImVec2.getCPtr(pos), pos, col, text_begin, text_end);
  }

  public void AddText(ImFont font, float font_size, ImVec2 pos, long col, String text_begin) {
    jimguiJNI.ImDrawList_AddText__SWIG_5(swigCPtr, this, ImFont.getCPtr(font), font, font_size, ImVec2.getCPtr(pos), pos, col, text_begin);
  }

  public void AddImage(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b, long col) {
    jimguiJNI.ImDrawList_AddImage__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, col);
  }

  public void AddImage(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b) {
    jimguiJNI.ImDrawList_AddImage__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b);
  }

  public void AddImage(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 uv_a) {
    jimguiJNI.ImDrawList_AddImage__SWIG_2(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(uv_a), uv_a);
  }

  public void AddImage(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b) {
    jimguiJNI.ImDrawList_AddImage__SWIG_3(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b);
  }

  public void AddImageQuad(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b, ImVec2 uv_c, ImVec2 uv_d, long col) {
    jimguiJNI.ImDrawList_AddImageQuad__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, ImVec2.getCPtr(uv_c), uv_c, ImVec2.getCPtr(uv_d), uv_d, col);
  }

  public void AddImageQuad(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b, ImVec2 uv_c, ImVec2 uv_d) {
    jimguiJNI.ImDrawList_AddImageQuad__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, ImVec2.getCPtr(uv_c), uv_c, ImVec2.getCPtr(uv_d), uv_d);
  }

  public void AddImageQuad(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b, ImVec2 uv_c) {
    jimguiJNI.ImDrawList_AddImageQuad__SWIG_2(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, ImVec2.getCPtr(uv_c), uv_c);
  }

  public void AddImageQuad(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b) {
    jimguiJNI.ImDrawList_AddImageQuad__SWIG_3(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b);
  }

  public void AddImageQuad(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a) {
    jimguiJNI.ImDrawList_AddImageQuad__SWIG_4(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, ImVec2.getCPtr(uv_a), uv_a);
  }

  public void AddImageQuad(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d) {
    jimguiJNI.ImDrawList_AddImageQuad__SWIG_5(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d);
  }

  public void AddImageRounded(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b, long col, float rounding, int rounding_corners) {
    jimguiJNI.ImDrawList_AddImageRounded__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, col, rounding, rounding_corners);
  }

  public void AddImageRounded(SWIGTYPE_p_void user_texture_id, ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b, long col, float rounding) {
    jimguiJNI.ImDrawList_AddImageRounded__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(user_texture_id), ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, col, rounding);
  }

  public void AddPolyline(ImVec2 points, int num_points, long col, boolean closed, float thickness) {
    jimguiJNI.ImDrawList_AddPolyline(swigCPtr, this, ImVec2.getCPtr(points), points, num_points, col, closed, thickness);
  }

  public void AddConvexPolyFilled(ImVec2 points, int num_points, long col) {
    jimguiJNI.ImDrawList_AddConvexPolyFilled(swigCPtr, this, ImVec2.getCPtr(points), points, num_points, col);
  }

  public void AddBezierCurve(ImVec2 pos0, ImVec2 cp0, ImVec2 cp1, ImVec2 pos1, long col, float thickness, int num_segments) {
    jimguiJNI.ImDrawList_AddBezierCurve__SWIG_0(swigCPtr, this, ImVec2.getCPtr(pos0), pos0, ImVec2.getCPtr(cp0), cp0, ImVec2.getCPtr(cp1), cp1, ImVec2.getCPtr(pos1), pos1, col, thickness, num_segments);
  }

  public void AddBezierCurve(ImVec2 pos0, ImVec2 cp0, ImVec2 cp1, ImVec2 pos1, long col, float thickness) {
    jimguiJNI.ImDrawList_AddBezierCurve__SWIG_1(swigCPtr, this, ImVec2.getCPtr(pos0), pos0, ImVec2.getCPtr(cp0), cp0, ImVec2.getCPtr(cp1), cp1, ImVec2.getCPtr(pos1), pos1, col, thickness);
  }

  public void PathClear() {
    jimguiJNI.ImDrawList_PathClear(swigCPtr, this);
  }

  public void PathLineTo(ImVec2 pos) {
    jimguiJNI.ImDrawList_PathLineTo(swigCPtr, this, ImVec2.getCPtr(pos), pos);
  }

  public void PathLineToMergeDuplicate(ImVec2 pos) {
    jimguiJNI.ImDrawList_PathLineToMergeDuplicate(swigCPtr, this, ImVec2.getCPtr(pos), pos);
  }

  public void PathFillConvex(long col) {
    jimguiJNI.ImDrawList_PathFillConvex(swigCPtr, this, col);
  }

  public void PathStroke(long col, boolean closed, float thickness) {
    jimguiJNI.ImDrawList_PathStroke__SWIG_0(swigCPtr, this, col, closed, thickness);
  }

  public void PathStroke(long col, boolean closed) {
    jimguiJNI.ImDrawList_PathStroke__SWIG_1(swigCPtr, this, col, closed);
  }

  public void PathArcTo(ImVec2 centre, float radius, float a_min, float a_max, int num_segments) {
    jimguiJNI.ImDrawList_PathArcTo__SWIG_0(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, a_min, a_max, num_segments);
  }

  public void PathArcTo(ImVec2 centre, float radius, float a_min, float a_max) {
    jimguiJNI.ImDrawList_PathArcTo__SWIG_1(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, a_min, a_max);
  }

  public void PathArcToFast(ImVec2 centre, float radius, int a_min_of_12, int a_max_of_12) {
    jimguiJNI.ImDrawList_PathArcToFast(swigCPtr, this, ImVec2.getCPtr(centre), centre, radius, a_min_of_12, a_max_of_12);
  }

  public void PathBezierCurveTo(ImVec2 p1, ImVec2 p2, ImVec2 p3, int num_segments) {
    jimguiJNI.ImDrawList_PathBezierCurveTo__SWIG_0(swigCPtr, this, ImVec2.getCPtr(p1), p1, ImVec2.getCPtr(p2), p2, ImVec2.getCPtr(p3), p3, num_segments);
  }

  public void PathBezierCurveTo(ImVec2 p1, ImVec2 p2, ImVec2 p3) {
    jimguiJNI.ImDrawList_PathBezierCurveTo__SWIG_1(swigCPtr, this, ImVec2.getCPtr(p1), p1, ImVec2.getCPtr(p2), p2, ImVec2.getCPtr(p3), p3);
  }

  public void PathRect(ImVec2 rect_min, ImVec2 rect_max, float rounding, int rounding_corners_flags) {
    jimguiJNI.ImDrawList_PathRect__SWIG_0(swigCPtr, this, ImVec2.getCPtr(rect_min), rect_min, ImVec2.getCPtr(rect_max), rect_max, rounding, rounding_corners_flags);
  }

  public void PathRect(ImVec2 rect_min, ImVec2 rect_max, float rounding) {
    jimguiJNI.ImDrawList_PathRect__SWIG_1(swigCPtr, this, ImVec2.getCPtr(rect_min), rect_min, ImVec2.getCPtr(rect_max), rect_max, rounding);
  }

  public void PathRect(ImVec2 rect_min, ImVec2 rect_max) {
    jimguiJNI.ImDrawList_PathRect__SWIG_2(swigCPtr, this, ImVec2.getCPtr(rect_min), rect_min, ImVec2.getCPtr(rect_max), rect_max);
  }

  public void ChannelsSplit(int channels_count) {
    jimguiJNI.ImDrawList_ChannelsSplit(swigCPtr, this, channels_count);
  }

  public void ChannelsMerge() {
    jimguiJNI.ImDrawList_ChannelsMerge(swigCPtr, this);
  }

  public void ChannelsSetCurrent(int channel_index) {
    jimguiJNI.ImDrawList_ChannelsSetCurrent(swigCPtr, this, channel_index);
  }

  public void AddCallback(SWIGTYPE_p_f_p_q_const__ImDrawList_p_q_const__ImDrawCmd__void callback, SWIGTYPE_p_void callback_data) {
    jimguiJNI.ImDrawList_AddCallback(swigCPtr, this, SWIGTYPE_p_f_p_q_const__ImDrawList_p_q_const__ImDrawCmd__void.getCPtr(callback), SWIGTYPE_p_void.getCPtr(callback_data));
  }

  public void AddDrawCmd() {
    jimguiJNI.ImDrawList_AddDrawCmd(swigCPtr, this);
  }

  public ImDrawList CloneOutput() {
    long cPtr = jimguiJNI.ImDrawList_CloneOutput(swigCPtr, this);
    return (cPtr == 0) ? null : new ImDrawList(cPtr, false);
  }

  public void Clear() {
    jimguiJNI.ImDrawList_Clear(swigCPtr, this);
  }

  public void ClearFreeMemory() {
    jimguiJNI.ImDrawList_ClearFreeMemory(swigCPtr, this);
  }

  public void PrimReserve(int idx_count, int vtx_count) {
    jimguiJNI.ImDrawList_PrimReserve(swigCPtr, this, idx_count, vtx_count);
  }

  public void PrimRect(ImVec2 a, ImVec2 b, long col) {
    jimguiJNI.ImDrawList_PrimRect(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, col);
  }

  public void PrimRectUV(ImVec2 a, ImVec2 b, ImVec2 uv_a, ImVec2 uv_b, long col) {
    jimguiJNI.ImDrawList_PrimRectUV(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, col);
  }

  public void PrimQuadUV(ImVec2 a, ImVec2 b, ImVec2 c, ImVec2 d, ImVec2 uv_a, ImVec2 uv_b, ImVec2 uv_c, ImVec2 uv_d, long col) {
    jimguiJNI.ImDrawList_PrimQuadUV(swigCPtr, this, ImVec2.getCPtr(a), a, ImVec2.getCPtr(b), b, ImVec2.getCPtr(c), c, ImVec2.getCPtr(d), d, ImVec2.getCPtr(uv_a), uv_a, ImVec2.getCPtr(uv_b), uv_b, ImVec2.getCPtr(uv_c), uv_c, ImVec2.getCPtr(uv_d), uv_d, col);
  }

  public void PrimWriteVtx(ImVec2 pos, ImVec2 uv, long col) {
    jimguiJNI.ImDrawList_PrimWriteVtx(swigCPtr, this, ImVec2.getCPtr(pos), pos, ImVec2.getCPtr(uv), uv, col);
  }

  public void PrimWriteIdx(int idx) {
    jimguiJNI.ImDrawList_PrimWriteIdx(swigCPtr, this, idx);
  }

  public void PrimVtx(ImVec2 pos, ImVec2 uv, long col) {
    jimguiJNI.ImDrawList_PrimVtx(swigCPtr, this, ImVec2.getCPtr(pos), pos, ImVec2.getCPtr(uv), uv, col);
  }

  public void UpdateClipRect() {
    jimguiJNI.ImDrawList_UpdateClipRect(swigCPtr, this);
  }

  public void UpdateTextureID() {
    jimguiJNI.ImDrawList_UpdateTextureID(swigCPtr, this);
  }

}
