/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImDrawChannel {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImDrawChannel(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImDrawChannel obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImDrawChannel(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCmdBuffer(SWIGTYPE_p_ImVectorT_ImDrawCmd_t value) {
    jimguiJNI.ImDrawChannel_CmdBuffer_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImDrawCmd_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImDrawCmd_t getCmdBuffer() {
    long cPtr = jimguiJNI.ImDrawChannel_CmdBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImDrawCmd_t(cPtr, false);
  }

  public void setIdxBuffer(SWIGTYPE_p_ImVectorT_unsigned_short_t value) {
    jimguiJNI.ImDrawChannel_IdxBuffer_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_unsigned_short_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_unsigned_short_t getIdxBuffer() {
    long cPtr = jimguiJNI.ImDrawChannel_IdxBuffer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_unsigned_short_t(cPtr, false);
  }

  public ImDrawChannel() {
    this(jimguiJNI.new_ImDrawChannel(), true);
  }

}
