/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImFontAtlasFlags_ {
  public final static ImFontAtlasFlags_ ImFontAtlasFlags_NoPowerOfTwoHeight = new ImFontAtlasFlags_("ImFontAtlasFlags_NoPowerOfTwoHeight", jimguiJNI.ImFontAtlasFlags_NoPowerOfTwoHeight_get());
  public final static ImFontAtlasFlags_ ImFontAtlasFlags_NoMouseCursors = new ImFontAtlasFlags_("ImFontAtlasFlags_NoMouseCursors", jimguiJNI.ImFontAtlasFlags_NoMouseCursors_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImFontAtlasFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImFontAtlasFlags_.class + " with value " + swigValue);
  }

  private ImFontAtlasFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImFontAtlasFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImFontAtlasFlags_(String swigName, ImFontAtlasFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImFontAtlasFlags_[] swigValues = { ImFontAtlasFlags_NoPowerOfTwoHeight, ImFontAtlasFlags_NoMouseCursors };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

