/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImFontGlyph {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImFontGlyph(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImFontGlyph obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImFontGlyph(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCodepoint(int value) {
    jimguiJNI.ImFontGlyph_Codepoint_set(swigCPtr, this, value);
  }

  public int getCodepoint() {
    return jimguiJNI.ImFontGlyph_Codepoint_get(swigCPtr, this);
  }

  public void setAdvanceX(float value) {
    jimguiJNI.ImFontGlyph_AdvanceX_set(swigCPtr, this, value);
  }

  public float getAdvanceX() {
    return jimguiJNI.ImFontGlyph_AdvanceX_get(swigCPtr, this);
  }

  public void setX0(float value) {
    jimguiJNI.ImFontGlyph_X0_set(swigCPtr, this, value);
  }

  public float getX0() {
    return jimguiJNI.ImFontGlyph_X0_get(swigCPtr, this);
  }

  public void setY0(float value) {
    jimguiJNI.ImFontGlyph_Y0_set(swigCPtr, this, value);
  }

  public float getY0() {
    return jimguiJNI.ImFontGlyph_Y0_get(swigCPtr, this);
  }

  public void setX1(float value) {
    jimguiJNI.ImFontGlyph_X1_set(swigCPtr, this, value);
  }

  public float getX1() {
    return jimguiJNI.ImFontGlyph_X1_get(swigCPtr, this);
  }

  public void setY1(float value) {
    jimguiJNI.ImFontGlyph_Y1_set(swigCPtr, this, value);
  }

  public float getY1() {
    return jimguiJNI.ImFontGlyph_Y1_get(swigCPtr, this);
  }

  public void setU0(float value) {
    jimguiJNI.ImFontGlyph_U0_set(swigCPtr, this, value);
  }

  public float getU0() {
    return jimguiJNI.ImFontGlyph_U0_get(swigCPtr, this);
  }

  public void setV0(float value) {
    jimguiJNI.ImFontGlyph_V0_set(swigCPtr, this, value);
  }

  public float getV0() {
    return jimguiJNI.ImFontGlyph_V0_get(swigCPtr, this);
  }

  public void setU1(float value) {
    jimguiJNI.ImFontGlyph_U1_set(swigCPtr, this, value);
  }

  public float getU1() {
    return jimguiJNI.ImFontGlyph_U1_get(swigCPtr, this);
  }

  public void setV1(float value) {
    jimguiJNI.ImFontGlyph_V1_set(swigCPtr, this, value);
  }

  public float getV1() {
    return jimguiJNI.ImFontGlyph_V1_get(swigCPtr, this);
  }

  public ImFontGlyph() {
    this(jimguiJNI.new_ImFontGlyph(), true);
  }

}
