/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImGuiPayload {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImGuiPayload(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImGuiPayload obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImGuiPayload(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setData(SWIGTYPE_p_void value) {
    jimguiJNI.ImGuiPayload_Data_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getData() {
    long cPtr = jimguiJNI.ImGuiPayload_Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setDataSize(int value) {
    jimguiJNI.ImGuiPayload_DataSize_set(swigCPtr, this, value);
  }

  public int getDataSize() {
    return jimguiJNI.ImGuiPayload_DataSize_get(swigCPtr, this);
  }

  public void setSourceId(long value) {
    jimguiJNI.ImGuiPayload_SourceId_set(swigCPtr, this, value);
  }

  public long getSourceId() {
    return jimguiJNI.ImGuiPayload_SourceId_get(swigCPtr, this);
  }

  public void setSourceParentId(long value) {
    jimguiJNI.ImGuiPayload_SourceParentId_set(swigCPtr, this, value);
  }

  public long getSourceParentId() {
    return jimguiJNI.ImGuiPayload_SourceParentId_get(swigCPtr, this);
  }

  public void setDataFrameCount(int value) {
    jimguiJNI.ImGuiPayload_DataFrameCount_set(swigCPtr, this, value);
  }

  public int getDataFrameCount() {
    return jimguiJNI.ImGuiPayload_DataFrameCount_get(swigCPtr, this);
  }

  public void setDataType(String value) {
    jimguiJNI.ImGuiPayload_DataType_set(swigCPtr, this, value);
  }

  public String getDataType() {
    return jimguiJNI.ImGuiPayload_DataType_get(swigCPtr, this);
  }

  public void setPreview(boolean value) {
    jimguiJNI.ImGuiPayload_Preview_set(swigCPtr, this, value);
  }

  public boolean getPreview() {
    return jimguiJNI.ImGuiPayload_Preview_get(swigCPtr, this);
  }

  public void setDelivery(boolean value) {
    jimguiJNI.ImGuiPayload_Delivery_set(swigCPtr, this, value);
  }

  public boolean getDelivery() {
    return jimguiJNI.ImGuiPayload_Delivery_get(swigCPtr, this);
  }

  public ImGuiPayload() {
    this(jimguiJNI.new_ImGuiPayload(), true);
  }

  public void Clear() {
    jimguiJNI.ImGuiPayload_Clear(swigCPtr, this);
  }

  public boolean IsDataType(String type) {
    return jimguiJNI.ImGuiPayload_IsDataType(swigCPtr, this, type);
  }

  public boolean IsPreview() {
    return jimguiJNI.ImGuiPayload_IsPreview(swigCPtr, this);
  }

  public boolean IsDelivery() {
    return jimguiJNI.ImGuiPayload_IsDelivery(swigCPtr, this);
  }

}
