/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImGuiListClipper {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImGuiListClipper(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImGuiListClipper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImGuiListClipper(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setStartPosY(float value) {
    jimguiJNI.ImGuiListClipper_StartPosY_set(swigCPtr, this, value);
  }

  public float getStartPosY() {
    return jimguiJNI.ImGuiListClipper_StartPosY_get(swigCPtr, this);
  }

  public void setItemsHeight(float value) {
    jimguiJNI.ImGuiListClipper_ItemsHeight_set(swigCPtr, this, value);
  }

  public float getItemsHeight() {
    return jimguiJNI.ImGuiListClipper_ItemsHeight_get(swigCPtr, this);
  }

  public void setItemsCount(int value) {
    jimguiJNI.ImGuiListClipper_ItemsCount_set(swigCPtr, this, value);
  }

  public int getItemsCount() {
    return jimguiJNI.ImGuiListClipper_ItemsCount_get(swigCPtr, this);
  }

  public void setStepNo(int value) {
    jimguiJNI.ImGuiListClipper_StepNo_set(swigCPtr, this, value);
  }

  public int getStepNo() {
    return jimguiJNI.ImGuiListClipper_StepNo_get(swigCPtr, this);
  }

  public void setDisplayStart(int value) {
    jimguiJNI.ImGuiListClipper_DisplayStart_set(swigCPtr, this, value);
  }

  public int getDisplayStart() {
    return jimguiJNI.ImGuiListClipper_DisplayStart_get(swigCPtr, this);
  }

  public void setDisplayEnd(int value) {
    jimguiJNI.ImGuiListClipper_DisplayEnd_set(swigCPtr, this, value);
  }

  public int getDisplayEnd() {
    return jimguiJNI.ImGuiListClipper_DisplayEnd_get(swigCPtr, this);
  }

  public ImGuiListClipper(int items_count, float items_height) {
    this(jimguiJNI.new_ImGuiListClipper__SWIG_0(items_count, items_height), true);
  }

  public ImGuiListClipper(int items_count) {
    this(jimguiJNI.new_ImGuiListClipper__SWIG_1(items_count), true);
  }

  public ImGuiListClipper() {
    this(jimguiJNI.new_ImGuiListClipper__SWIG_2(), true);
  }

  public boolean Step() {
    return jimguiJNI.ImGuiListClipper_Step(swigCPtr, this);
  }

  public void Begin(int items_count, float items_height) {
    jimguiJNI.ImGuiListClipper_Begin__SWIG_0(swigCPtr, this, items_count, items_height);
  }

  public void Begin(int items_count) {
    jimguiJNI.ImGuiListClipper_Begin__SWIG_1(swigCPtr, this, items_count);
  }

  public void End() {
    jimguiJNI.ImGuiListClipper_End(swigCPtr, this);
  }

}
