/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiStyleVar_ {
  public final static ImGuiStyleVar_ ImGuiStyleVar_Alpha = new ImGuiStyleVar_("ImGuiStyleVar_Alpha");
  public final static ImGuiStyleVar_ ImGuiStyleVar_WindowPadding = new ImGuiStyleVar_("ImGuiStyleVar_WindowPadding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_WindowRounding = new ImGuiStyleVar_("ImGuiStyleVar_WindowRounding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_WindowBorderSize = new ImGuiStyleVar_("ImGuiStyleVar_WindowBorderSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_WindowMinSize = new ImGuiStyleVar_("ImGuiStyleVar_WindowMinSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_WindowTitleAlign = new ImGuiStyleVar_("ImGuiStyleVar_WindowTitleAlign");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ChildRounding = new ImGuiStyleVar_("ImGuiStyleVar_ChildRounding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ChildBorderSize = new ImGuiStyleVar_("ImGuiStyleVar_ChildBorderSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_PopupRounding = new ImGuiStyleVar_("ImGuiStyleVar_PopupRounding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_PopupBorderSize = new ImGuiStyleVar_("ImGuiStyleVar_PopupBorderSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_FramePadding = new ImGuiStyleVar_("ImGuiStyleVar_FramePadding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_FrameRounding = new ImGuiStyleVar_("ImGuiStyleVar_FrameRounding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_FrameBorderSize = new ImGuiStyleVar_("ImGuiStyleVar_FrameBorderSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ItemSpacing = new ImGuiStyleVar_("ImGuiStyleVar_ItemSpacing");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ItemInnerSpacing = new ImGuiStyleVar_("ImGuiStyleVar_ItemInnerSpacing");
  public final static ImGuiStyleVar_ ImGuiStyleVar_IndentSpacing = new ImGuiStyleVar_("ImGuiStyleVar_IndentSpacing");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ScrollbarSize = new ImGuiStyleVar_("ImGuiStyleVar_ScrollbarSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ScrollbarRounding = new ImGuiStyleVar_("ImGuiStyleVar_ScrollbarRounding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_GrabMinSize = new ImGuiStyleVar_("ImGuiStyleVar_GrabMinSize");
  public final static ImGuiStyleVar_ ImGuiStyleVar_GrabRounding = new ImGuiStyleVar_("ImGuiStyleVar_GrabRounding");
  public final static ImGuiStyleVar_ ImGuiStyleVar_ButtonTextAlign = new ImGuiStyleVar_("ImGuiStyleVar_ButtonTextAlign");
  public final static ImGuiStyleVar_ ImGuiStyleVar_COUNT = new ImGuiStyleVar_("ImGuiStyleVar_COUNT");
  public final static ImGuiStyleVar_ ImGuiStyleVar_Count_ = new ImGuiStyleVar_("ImGuiStyleVar_Count_", jimguiJNI.ImGuiStyleVar_Count__get());
  public final static ImGuiStyleVar_ ImGuiStyleVar_ChildWindowRounding = new ImGuiStyleVar_("ImGuiStyleVar_ChildWindowRounding", jimguiJNI.ImGuiStyleVar_ChildWindowRounding_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiStyleVar_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiStyleVar_.class + " with value " + swigValue);
  }

  private ImGuiStyleVar_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiStyleVar_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiStyleVar_(String swigName, ImGuiStyleVar_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiStyleVar_[] swigValues = { ImGuiStyleVar_Alpha, ImGuiStyleVar_WindowPadding, ImGuiStyleVar_WindowRounding, ImGuiStyleVar_WindowBorderSize, ImGuiStyleVar_WindowMinSize, ImGuiStyleVar_WindowTitleAlign, ImGuiStyleVar_ChildRounding, ImGuiStyleVar_ChildBorderSize, ImGuiStyleVar_PopupRounding, ImGuiStyleVar_PopupBorderSize, ImGuiStyleVar_FramePadding, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_ItemSpacing, ImGuiStyleVar_ItemInnerSpacing, ImGuiStyleVar_IndentSpacing, ImGuiStyleVar_ScrollbarSize, ImGuiStyleVar_ScrollbarRounding, ImGuiStyleVar_GrabMinSize, ImGuiStyleVar_GrabRounding, ImGuiStyleVar_ButtonTextAlign, ImGuiStyleVar_COUNT, ImGuiStyleVar_Count_, ImGuiStyleVar_ChildWindowRounding };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

