/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiWindowFlags_ {
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_None = new ImGuiWindowFlags_("ImGuiWindowFlags_None", jimguiJNI.ImGuiWindowFlags_None_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoTitleBar = new ImGuiWindowFlags_("ImGuiWindowFlags_NoTitleBar", jimguiJNI.ImGuiWindowFlags_NoTitleBar_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoResize = new ImGuiWindowFlags_("ImGuiWindowFlags_NoResize", jimguiJNI.ImGuiWindowFlags_NoResize_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoMove = new ImGuiWindowFlags_("ImGuiWindowFlags_NoMove", jimguiJNI.ImGuiWindowFlags_NoMove_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoScrollbar = new ImGuiWindowFlags_("ImGuiWindowFlags_NoScrollbar", jimguiJNI.ImGuiWindowFlags_NoScrollbar_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoScrollWithMouse = new ImGuiWindowFlags_("ImGuiWindowFlags_NoScrollWithMouse", jimguiJNI.ImGuiWindowFlags_NoScrollWithMouse_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoCollapse = new ImGuiWindowFlags_("ImGuiWindowFlags_NoCollapse", jimguiJNI.ImGuiWindowFlags_NoCollapse_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_AlwaysAutoResize = new ImGuiWindowFlags_("ImGuiWindowFlags_AlwaysAutoResize", jimguiJNI.ImGuiWindowFlags_AlwaysAutoResize_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoSavedSettings = new ImGuiWindowFlags_("ImGuiWindowFlags_NoSavedSettings", jimguiJNI.ImGuiWindowFlags_NoSavedSettings_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoInputs = new ImGuiWindowFlags_("ImGuiWindowFlags_NoInputs", jimguiJNI.ImGuiWindowFlags_NoInputs_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_MenuBar = new ImGuiWindowFlags_("ImGuiWindowFlags_MenuBar", jimguiJNI.ImGuiWindowFlags_MenuBar_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_HorizontalScrollbar = new ImGuiWindowFlags_("ImGuiWindowFlags_HorizontalScrollbar", jimguiJNI.ImGuiWindowFlags_HorizontalScrollbar_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoFocusOnAppearing = new ImGuiWindowFlags_("ImGuiWindowFlags_NoFocusOnAppearing", jimguiJNI.ImGuiWindowFlags_NoFocusOnAppearing_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoBringToFrontOnFocus = new ImGuiWindowFlags_("ImGuiWindowFlags_NoBringToFrontOnFocus", jimguiJNI.ImGuiWindowFlags_NoBringToFrontOnFocus_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_AlwaysVerticalScrollbar = new ImGuiWindowFlags_("ImGuiWindowFlags_AlwaysVerticalScrollbar", jimguiJNI.ImGuiWindowFlags_AlwaysVerticalScrollbar_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_AlwaysHorizontalScrollbar = new ImGuiWindowFlags_("ImGuiWindowFlags_AlwaysHorizontalScrollbar", jimguiJNI.ImGuiWindowFlags_AlwaysHorizontalScrollbar_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_AlwaysUseWindowPadding = new ImGuiWindowFlags_("ImGuiWindowFlags_AlwaysUseWindowPadding", jimguiJNI.ImGuiWindowFlags_AlwaysUseWindowPadding_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoNavInputs = new ImGuiWindowFlags_("ImGuiWindowFlags_NoNavInputs", jimguiJNI.ImGuiWindowFlags_NoNavInputs_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoNavFocus = new ImGuiWindowFlags_("ImGuiWindowFlags_NoNavFocus", jimguiJNI.ImGuiWindowFlags_NoNavFocus_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NoNav = new ImGuiWindowFlags_("ImGuiWindowFlags_NoNav", jimguiJNI.ImGuiWindowFlags_NoNav_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_NavFlattened = new ImGuiWindowFlags_("ImGuiWindowFlags_NavFlattened", jimguiJNI.ImGuiWindowFlags_NavFlattened_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_ChildWindow = new ImGuiWindowFlags_("ImGuiWindowFlags_ChildWindow", jimguiJNI.ImGuiWindowFlags_ChildWindow_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_Tooltip = new ImGuiWindowFlags_("ImGuiWindowFlags_Tooltip", jimguiJNI.ImGuiWindowFlags_Tooltip_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_Popup = new ImGuiWindowFlags_("ImGuiWindowFlags_Popup", jimguiJNI.ImGuiWindowFlags_Popup_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_Modal = new ImGuiWindowFlags_("ImGuiWindowFlags_Modal", jimguiJNI.ImGuiWindowFlags_Modal_get());
  public final static ImGuiWindowFlags_ ImGuiWindowFlags_ChildMenu = new ImGuiWindowFlags_("ImGuiWindowFlags_ChildMenu", jimguiJNI.ImGuiWindowFlags_ChildMenu_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiWindowFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiWindowFlags_.class + " with value " + swigValue);
  }

  private ImGuiWindowFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiWindowFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiWindowFlags_(String swigName, ImGuiWindowFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiWindowFlags_[] swigValues = { ImGuiWindowFlags_None, ImGuiWindowFlags_NoTitleBar, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoSavedSettings, ImGuiWindowFlags_NoInputs, ImGuiWindowFlags_MenuBar, ImGuiWindowFlags_HorizontalScrollbar, ImGuiWindowFlags_NoFocusOnAppearing, ImGuiWindowFlags_NoBringToFrontOnFocus, ImGuiWindowFlags_AlwaysVerticalScrollbar, ImGuiWindowFlags_AlwaysHorizontalScrollbar, ImGuiWindowFlags_AlwaysUseWindowPadding, ImGuiWindowFlags_NoNavInputs, ImGuiWindowFlags_NoNavFocus, ImGuiWindowFlags_NoNav, ImGuiWindowFlags_NavFlattened, ImGuiWindowFlags_ChildWindow, ImGuiWindowFlags_Tooltip, ImGuiWindowFlags_Popup, ImGuiWindowFlags_Modal, ImGuiWindowFlags_ChildMenu };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

