/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiSelectableFlags_ {
  public final static ImGuiSelectableFlags_ ImGuiSelectableFlags_None = new ImGuiSelectableFlags_("ImGuiSelectableFlags_None", jimguiJNI.ImGuiSelectableFlags_None_get());
  public final static ImGuiSelectableFlags_ ImGuiSelectableFlags_DontClosePopups = new ImGuiSelectableFlags_("ImGuiSelectableFlags_DontClosePopups", jimguiJNI.ImGuiSelectableFlags_DontClosePopups_get());
  public final static ImGuiSelectableFlags_ ImGuiSelectableFlags_SpanAllColumns = new ImGuiSelectableFlags_("ImGuiSelectableFlags_SpanAllColumns", jimguiJNI.ImGuiSelectableFlags_SpanAllColumns_get());
  public final static ImGuiSelectableFlags_ ImGuiSelectableFlags_AllowDoubleClick = new ImGuiSelectableFlags_("ImGuiSelectableFlags_AllowDoubleClick", jimguiJNI.ImGuiSelectableFlags_AllowDoubleClick_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiSelectableFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiSelectableFlags_.class + " with value " + swigValue);
  }

  private ImGuiSelectableFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiSelectableFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiSelectableFlags_(String swigName, ImGuiSelectableFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiSelectableFlags_[] swigValues = { ImGuiSelectableFlags_None, ImGuiSelectableFlags_DontClosePopups, ImGuiSelectableFlags_SpanAllColumns, ImGuiSelectableFlags_AllowDoubleClick };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

