/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiCol_ {
  public final static ImGuiCol_ ImGuiCol_Text = new ImGuiCol_("ImGuiCol_Text");
  public final static ImGuiCol_ ImGuiCol_TextDisabled = new ImGuiCol_("ImGuiCol_TextDisabled");
  public final static ImGuiCol_ ImGuiCol_WindowBg = new ImGuiCol_("ImGuiCol_WindowBg");
  public final static ImGuiCol_ ImGuiCol_ChildBg = new ImGuiCol_("ImGuiCol_ChildBg");
  public final static ImGuiCol_ ImGuiCol_PopupBg = new ImGuiCol_("ImGuiCol_PopupBg");
  public final static ImGuiCol_ ImGuiCol_Border = new ImGuiCol_("ImGuiCol_Border");
  public final static ImGuiCol_ ImGuiCol_BorderShadow = new ImGuiCol_("ImGuiCol_BorderShadow");
  public final static ImGuiCol_ ImGuiCol_FrameBg = new ImGuiCol_("ImGuiCol_FrameBg");
  public final static ImGuiCol_ ImGuiCol_FrameBgHovered = new ImGuiCol_("ImGuiCol_FrameBgHovered");
  public final static ImGuiCol_ ImGuiCol_FrameBgActive = new ImGuiCol_("ImGuiCol_FrameBgActive");
  public final static ImGuiCol_ ImGuiCol_TitleBg = new ImGuiCol_("ImGuiCol_TitleBg");
  public final static ImGuiCol_ ImGuiCol_TitleBgActive = new ImGuiCol_("ImGuiCol_TitleBgActive");
  public final static ImGuiCol_ ImGuiCol_TitleBgCollapsed = new ImGuiCol_("ImGuiCol_TitleBgCollapsed");
  public final static ImGuiCol_ ImGuiCol_MenuBarBg = new ImGuiCol_("ImGuiCol_MenuBarBg");
  public final static ImGuiCol_ ImGuiCol_ScrollbarBg = new ImGuiCol_("ImGuiCol_ScrollbarBg");
  public final static ImGuiCol_ ImGuiCol_ScrollbarGrab = new ImGuiCol_("ImGuiCol_ScrollbarGrab");
  public final static ImGuiCol_ ImGuiCol_ScrollbarGrabHovered = new ImGuiCol_("ImGuiCol_ScrollbarGrabHovered");
  public final static ImGuiCol_ ImGuiCol_ScrollbarGrabActive = new ImGuiCol_("ImGuiCol_ScrollbarGrabActive");
  public final static ImGuiCol_ ImGuiCol_CheckMark = new ImGuiCol_("ImGuiCol_CheckMark");
  public final static ImGuiCol_ ImGuiCol_SliderGrab = new ImGuiCol_("ImGuiCol_SliderGrab");
  public final static ImGuiCol_ ImGuiCol_SliderGrabActive = new ImGuiCol_("ImGuiCol_SliderGrabActive");
  public final static ImGuiCol_ ImGuiCol_Button = new ImGuiCol_("ImGuiCol_Button");
  public final static ImGuiCol_ ImGuiCol_ButtonHovered = new ImGuiCol_("ImGuiCol_ButtonHovered");
  public final static ImGuiCol_ ImGuiCol_ButtonActive = new ImGuiCol_("ImGuiCol_ButtonActive");
  public final static ImGuiCol_ ImGuiCol_Header = new ImGuiCol_("ImGuiCol_Header");
  public final static ImGuiCol_ ImGuiCol_HeaderHovered = new ImGuiCol_("ImGuiCol_HeaderHovered");
  public final static ImGuiCol_ ImGuiCol_HeaderActive = new ImGuiCol_("ImGuiCol_HeaderActive");
  public final static ImGuiCol_ ImGuiCol_Separator = new ImGuiCol_("ImGuiCol_Separator");
  public final static ImGuiCol_ ImGuiCol_SeparatorHovered = new ImGuiCol_("ImGuiCol_SeparatorHovered");
  public final static ImGuiCol_ ImGuiCol_SeparatorActive = new ImGuiCol_("ImGuiCol_SeparatorActive");
  public final static ImGuiCol_ ImGuiCol_ResizeGrip = new ImGuiCol_("ImGuiCol_ResizeGrip");
  public final static ImGuiCol_ ImGuiCol_ResizeGripHovered = new ImGuiCol_("ImGuiCol_ResizeGripHovered");
  public final static ImGuiCol_ ImGuiCol_ResizeGripActive = new ImGuiCol_("ImGuiCol_ResizeGripActive");
  public final static ImGuiCol_ ImGuiCol_PlotLines = new ImGuiCol_("ImGuiCol_PlotLines");
  public final static ImGuiCol_ ImGuiCol_PlotLinesHovered = new ImGuiCol_("ImGuiCol_PlotLinesHovered");
  public final static ImGuiCol_ ImGuiCol_PlotHistogram = new ImGuiCol_("ImGuiCol_PlotHistogram");
  public final static ImGuiCol_ ImGuiCol_PlotHistogramHovered = new ImGuiCol_("ImGuiCol_PlotHistogramHovered");
  public final static ImGuiCol_ ImGuiCol_TextSelectedBg = new ImGuiCol_("ImGuiCol_TextSelectedBg");
  public final static ImGuiCol_ ImGuiCol_DragDropTarget = new ImGuiCol_("ImGuiCol_DragDropTarget");
  public final static ImGuiCol_ ImGuiCol_NavHighlight = new ImGuiCol_("ImGuiCol_NavHighlight");
  public final static ImGuiCol_ ImGuiCol_NavWindowListHighlight = new ImGuiCol_("ImGuiCol_NavWindowListHighlight");
  public final static ImGuiCol_ ImGuiCol_NavWindowListDimBg = new ImGuiCol_("ImGuiCol_NavWindowListDimBg");
  public final static ImGuiCol_ ImGuiCol_ModalWindowDimBg = new ImGuiCol_("ImGuiCol_ModalWindowDimBg");
  public final static ImGuiCol_ ImGuiCol_COUNT = new ImGuiCol_("ImGuiCol_COUNT");
  public final static ImGuiCol_ ImGuiCol_ChildWindowBg = new ImGuiCol_("ImGuiCol_ChildWindowBg", jimguiJNI.ImGuiCol_ChildWindowBg_get());
  public final static ImGuiCol_ ImGuiCol_Column = new ImGuiCol_("ImGuiCol_Column", jimguiJNI.ImGuiCol_Column_get());
  public final static ImGuiCol_ ImGuiCol_ColumnHovered = new ImGuiCol_("ImGuiCol_ColumnHovered", jimguiJNI.ImGuiCol_ColumnHovered_get());
  public final static ImGuiCol_ ImGuiCol_ColumnActive = new ImGuiCol_("ImGuiCol_ColumnActive", jimguiJNI.ImGuiCol_ColumnActive_get());
  public final static ImGuiCol_ ImGuiCol_ModalWindowDarkening = new ImGuiCol_("ImGuiCol_ModalWindowDarkening", jimguiJNI.ImGuiCol_ModalWindowDarkening_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiCol_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiCol_.class + " with value " + swigValue);
  }

  private ImGuiCol_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiCol_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiCol_(String swigName, ImGuiCol_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiCol_[] swigValues = { ImGuiCol_Text, ImGuiCol_TextDisabled, ImGuiCol_WindowBg, ImGuiCol_ChildBg, ImGuiCol_PopupBg, ImGuiCol_Border, ImGuiCol_BorderShadow, ImGuiCol_FrameBg, ImGuiCol_FrameBgHovered, ImGuiCol_FrameBgActive, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_TitleBgCollapsed, ImGuiCol_MenuBarBg, ImGuiCol_ScrollbarBg, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_ScrollbarGrabActive, ImGuiCol_CheckMark, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiCol_Button, ImGuiCol_ButtonHovered, ImGuiCol_ButtonActive, ImGuiCol_Header, ImGuiCol_HeaderHovered, ImGuiCol_HeaderActive, ImGuiCol_Separator, ImGuiCol_SeparatorHovered, ImGuiCol_SeparatorActive, ImGuiCol_ResizeGrip, ImGuiCol_ResizeGripHovered, ImGuiCol_ResizeGripActive, ImGuiCol_PlotLines, ImGuiCol_PlotLinesHovered, ImGuiCol_PlotHistogram, ImGuiCol_PlotHistogramHovered, ImGuiCol_TextSelectedBg, ImGuiCol_DragDropTarget, ImGuiCol_NavHighlight, ImGuiCol_NavWindowListHighlight, ImGuiCol_NavWindowListDimBg, ImGuiCol_ModalWindowDimBg, ImGuiCol_COUNT, ImGuiCol_ChildWindowBg, ImGuiCol_Column, ImGuiCol_ColumnHovered, ImGuiCol_ColumnActive, ImGuiCol_ModalWindowDarkening };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

