/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiDragDropFlags_ {
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_None = new ImGuiDragDropFlags_("ImGuiDragDropFlags_None", jimguiJNI.ImGuiDragDropFlags_None_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_SourceNoPreviewTooltip = new ImGuiDragDropFlags_("ImGuiDragDropFlags_SourceNoPreviewTooltip", jimguiJNI.ImGuiDragDropFlags_SourceNoPreviewTooltip_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_SourceNoDisableHover = new ImGuiDragDropFlags_("ImGuiDragDropFlags_SourceNoDisableHover", jimguiJNI.ImGuiDragDropFlags_SourceNoDisableHover_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_SourceNoHoldToOpenOthers = new ImGuiDragDropFlags_("ImGuiDragDropFlags_SourceNoHoldToOpenOthers", jimguiJNI.ImGuiDragDropFlags_SourceNoHoldToOpenOthers_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_SourceAllowNullID = new ImGuiDragDropFlags_("ImGuiDragDropFlags_SourceAllowNullID", jimguiJNI.ImGuiDragDropFlags_SourceAllowNullID_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_SourceExtern = new ImGuiDragDropFlags_("ImGuiDragDropFlags_SourceExtern", jimguiJNI.ImGuiDragDropFlags_SourceExtern_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_AcceptBeforeDelivery = new ImGuiDragDropFlags_("ImGuiDragDropFlags_AcceptBeforeDelivery", jimguiJNI.ImGuiDragDropFlags_AcceptBeforeDelivery_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_AcceptNoDrawDefaultRect = new ImGuiDragDropFlags_("ImGuiDragDropFlags_AcceptNoDrawDefaultRect", jimguiJNI.ImGuiDragDropFlags_AcceptNoDrawDefaultRect_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_AcceptNoPreviewTooltip = new ImGuiDragDropFlags_("ImGuiDragDropFlags_AcceptNoPreviewTooltip", jimguiJNI.ImGuiDragDropFlags_AcceptNoPreviewTooltip_get());
  public final static ImGuiDragDropFlags_ ImGuiDragDropFlags_AcceptPeekOnly = new ImGuiDragDropFlags_("ImGuiDragDropFlags_AcceptPeekOnly", jimguiJNI.ImGuiDragDropFlags_AcceptPeekOnly_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiDragDropFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiDragDropFlags_.class + " with value " + swigValue);
  }

  private ImGuiDragDropFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiDragDropFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiDragDropFlags_(String swigName, ImGuiDragDropFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiDragDropFlags_[] swigValues = { ImGuiDragDropFlags_None, ImGuiDragDropFlags_SourceNoPreviewTooltip, ImGuiDragDropFlags_SourceNoDisableHover, ImGuiDragDropFlags_SourceNoHoldToOpenOthers, ImGuiDragDropFlags_SourceAllowNullID, ImGuiDragDropFlags_SourceExtern, ImGuiDragDropFlags_AcceptBeforeDelivery, ImGuiDragDropFlags_AcceptNoDrawDefaultRect, ImGuiDragDropFlags_AcceptNoPreviewTooltip, ImGuiDragDropFlags_AcceptPeekOnly };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

