/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiDir_ {
  public final static ImGuiDir_ ImGuiDir_None = new ImGuiDir_("ImGuiDir_None", jimguiJNI.ImGuiDir_None_get());
  public final static ImGuiDir_ ImGuiDir_Left = new ImGuiDir_("ImGuiDir_Left", jimguiJNI.ImGuiDir_Left_get());
  public final static ImGuiDir_ ImGuiDir_Right = new ImGuiDir_("ImGuiDir_Right", jimguiJNI.ImGuiDir_Right_get());
  public final static ImGuiDir_ ImGuiDir_Up = new ImGuiDir_("ImGuiDir_Up", jimguiJNI.ImGuiDir_Up_get());
  public final static ImGuiDir_ ImGuiDir_Down = new ImGuiDir_("ImGuiDir_Down", jimguiJNI.ImGuiDir_Down_get());
  public final static ImGuiDir_ ImGuiDir_COUNT = new ImGuiDir_("ImGuiDir_COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiDir_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiDir_.class + " with value " + swigValue);
  }

  private ImGuiDir_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiDir_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiDir_(String swigName, ImGuiDir_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiDir_[] swigValues = { ImGuiDir_None, ImGuiDir_Left, ImGuiDir_Right, ImGuiDir_Up, ImGuiDir_Down, ImGuiDir_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

