/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImGuiSizeCallbackData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImGuiSizeCallbackData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImGuiSizeCallbackData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImGuiSizeCallbackData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUserData(SWIGTYPE_p_void value) {
    jimguiJNI.ImGuiSizeCallbackData_UserData_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserData() {
    long cPtr = jimguiJNI.ImGuiSizeCallbackData_UserData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setPos(ImVec2 value) {
    jimguiJNI.ImGuiSizeCallbackData_Pos_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getPos() {
    long cPtr = jimguiJNI.ImGuiSizeCallbackData_Pos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setCurrentSize(ImVec2 value) {
    jimguiJNI.ImGuiSizeCallbackData_CurrentSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getCurrentSize() {
    long cPtr = jimguiJNI.ImGuiSizeCallbackData_CurrentSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDesiredSize(ImVec2 value) {
    jimguiJNI.ImGuiSizeCallbackData_DesiredSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDesiredSize() {
    long cPtr = jimguiJNI.ImGuiSizeCallbackData_DesiredSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public ImGuiSizeCallbackData() {
    this(jimguiJNI.new_ImGuiSizeCallbackData(), true);
  }

}
