/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiMouseCursor_ {
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_None = new ImGuiMouseCursor_("ImGuiMouseCursor_None", jimguiJNI.ImGuiMouseCursor_None_get());
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_Arrow = new ImGuiMouseCursor_("ImGuiMouseCursor_Arrow", jimguiJNI.ImGuiMouseCursor_Arrow_get());
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_TextInput = new ImGuiMouseCursor_("ImGuiMouseCursor_TextInput");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_ResizeAll = new ImGuiMouseCursor_("ImGuiMouseCursor_ResizeAll");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_ResizeNS = new ImGuiMouseCursor_("ImGuiMouseCursor_ResizeNS");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_ResizeEW = new ImGuiMouseCursor_("ImGuiMouseCursor_ResizeEW");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_ResizeNESW = new ImGuiMouseCursor_("ImGuiMouseCursor_ResizeNESW");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_ResizeNWSE = new ImGuiMouseCursor_("ImGuiMouseCursor_ResizeNWSE");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_Hand = new ImGuiMouseCursor_("ImGuiMouseCursor_Hand");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_COUNT = new ImGuiMouseCursor_("ImGuiMouseCursor_COUNT");
  public final static ImGuiMouseCursor_ ImGuiMouseCursor_Count_ = new ImGuiMouseCursor_("ImGuiMouseCursor_Count_", jimguiJNI.ImGuiMouseCursor_Count__get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiMouseCursor_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiMouseCursor_.class + " with value " + swigValue);
  }

  private ImGuiMouseCursor_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiMouseCursor_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiMouseCursor_(String swigName, ImGuiMouseCursor_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiMouseCursor_[] swigValues = { ImGuiMouseCursor_None, ImGuiMouseCursor_Arrow, ImGuiMouseCursor_TextInput, ImGuiMouseCursor_ResizeAll, ImGuiMouseCursor_ResizeNS, ImGuiMouseCursor_ResizeEW, ImGuiMouseCursor_ResizeNESW, ImGuiMouseCursor_ResizeNWSE, ImGuiMouseCursor_Hand, ImGuiMouseCursor_COUNT, ImGuiMouseCursor_Count_ };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

