/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiConfigFlags_ {
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_NavEnableKeyboard = new ImGuiConfigFlags_("ImGuiConfigFlags_NavEnableKeyboard", jimguiJNI.ImGuiConfigFlags_NavEnableKeyboard_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_NavEnableGamepad = new ImGuiConfigFlags_("ImGuiConfigFlags_NavEnableGamepad", jimguiJNI.ImGuiConfigFlags_NavEnableGamepad_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_NavEnableSetMousePos = new ImGuiConfigFlags_("ImGuiConfigFlags_NavEnableSetMousePos", jimguiJNI.ImGuiConfigFlags_NavEnableSetMousePos_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_NavNoCaptureKeyboard = new ImGuiConfigFlags_("ImGuiConfigFlags_NavNoCaptureKeyboard", jimguiJNI.ImGuiConfigFlags_NavNoCaptureKeyboard_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_NoMouse = new ImGuiConfigFlags_("ImGuiConfigFlags_NoMouse", jimguiJNI.ImGuiConfigFlags_NoMouse_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_NoMouseCursorChange = new ImGuiConfigFlags_("ImGuiConfigFlags_NoMouseCursorChange", jimguiJNI.ImGuiConfigFlags_NoMouseCursorChange_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_IsSRGB = new ImGuiConfigFlags_("ImGuiConfigFlags_IsSRGB", jimguiJNI.ImGuiConfigFlags_IsSRGB_get());
  public final static ImGuiConfigFlags_ ImGuiConfigFlags_IsTouchScreen = new ImGuiConfigFlags_("ImGuiConfigFlags_IsTouchScreen", jimguiJNI.ImGuiConfigFlags_IsTouchScreen_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiConfigFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiConfigFlags_.class + " with value " + swigValue);
  }

  private ImGuiConfigFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiConfigFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiConfigFlags_(String swigName, ImGuiConfigFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiConfigFlags_[] swigValues = { ImGuiConfigFlags_NavEnableKeyboard, ImGuiConfigFlags_NavEnableGamepad, ImGuiConfigFlags_NavEnableSetMousePos, ImGuiConfigFlags_NavNoCaptureKeyboard, ImGuiConfigFlags_NoMouse, ImGuiConfigFlags_NoMouseCursorChange, ImGuiConfigFlags_IsSRGB, ImGuiConfigFlags_IsTouchScreen };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

