/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiDataType_ {
  public final static ImGuiDataType_ ImGuiDataType_S32 = new ImGuiDataType_("ImGuiDataType_S32");
  public final static ImGuiDataType_ ImGuiDataType_U32 = new ImGuiDataType_("ImGuiDataType_U32");
  public final static ImGuiDataType_ ImGuiDataType_S64 = new ImGuiDataType_("ImGuiDataType_S64");
  public final static ImGuiDataType_ ImGuiDataType_U64 = new ImGuiDataType_("ImGuiDataType_U64");
  public final static ImGuiDataType_ ImGuiDataType_Float = new ImGuiDataType_("ImGuiDataType_Float");
  public final static ImGuiDataType_ ImGuiDataType_Double = new ImGuiDataType_("ImGuiDataType_Double");
  public final static ImGuiDataType_ ImGuiDataType_COUNT = new ImGuiDataType_("ImGuiDataType_COUNT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiDataType_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiDataType_.class + " with value " + swigValue);
  }

  private ImGuiDataType_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiDataType_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiDataType_(String swigName, ImGuiDataType_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiDataType_[] swigValues = { ImGuiDataType_S32, ImGuiDataType_U32, ImGuiDataType_S64, ImGuiDataType_U64, ImGuiDataType_Float, ImGuiDataType_Double, ImGuiDataType_COUNT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

