/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiNavInput_ {
  public final static ImGuiNavInput_ ImGuiNavInput_Activate = new ImGuiNavInput_("ImGuiNavInput_Activate");
  public final static ImGuiNavInput_ ImGuiNavInput_Cancel = new ImGuiNavInput_("ImGuiNavInput_Cancel");
  public final static ImGuiNavInput_ ImGuiNavInput_Input = new ImGuiNavInput_("ImGuiNavInput_Input");
  public final static ImGuiNavInput_ ImGuiNavInput_Menu = new ImGuiNavInput_("ImGuiNavInput_Menu");
  public final static ImGuiNavInput_ ImGuiNavInput_DpadLeft = new ImGuiNavInput_("ImGuiNavInput_DpadLeft");
  public final static ImGuiNavInput_ ImGuiNavInput_DpadRight = new ImGuiNavInput_("ImGuiNavInput_DpadRight");
  public final static ImGuiNavInput_ ImGuiNavInput_DpadUp = new ImGuiNavInput_("ImGuiNavInput_DpadUp");
  public final static ImGuiNavInput_ ImGuiNavInput_DpadDown = new ImGuiNavInput_("ImGuiNavInput_DpadDown");
  public final static ImGuiNavInput_ ImGuiNavInput_LStickLeft = new ImGuiNavInput_("ImGuiNavInput_LStickLeft");
  public final static ImGuiNavInput_ ImGuiNavInput_LStickRight = new ImGuiNavInput_("ImGuiNavInput_LStickRight");
  public final static ImGuiNavInput_ ImGuiNavInput_LStickUp = new ImGuiNavInput_("ImGuiNavInput_LStickUp");
  public final static ImGuiNavInput_ ImGuiNavInput_LStickDown = new ImGuiNavInput_("ImGuiNavInput_LStickDown");
  public final static ImGuiNavInput_ ImGuiNavInput_FocusPrev = new ImGuiNavInput_("ImGuiNavInput_FocusPrev");
  public final static ImGuiNavInput_ ImGuiNavInput_FocusNext = new ImGuiNavInput_("ImGuiNavInput_FocusNext");
  public final static ImGuiNavInput_ ImGuiNavInput_TweakSlow = new ImGuiNavInput_("ImGuiNavInput_TweakSlow");
  public final static ImGuiNavInput_ ImGuiNavInput_TweakFast = new ImGuiNavInput_("ImGuiNavInput_TweakFast");
  public final static ImGuiNavInput_ ImGuiNavInput_KeyMenu_ = new ImGuiNavInput_("ImGuiNavInput_KeyMenu_");
  public final static ImGuiNavInput_ ImGuiNavInput_KeyLeft_ = new ImGuiNavInput_("ImGuiNavInput_KeyLeft_");
  public final static ImGuiNavInput_ ImGuiNavInput_KeyRight_ = new ImGuiNavInput_("ImGuiNavInput_KeyRight_");
  public final static ImGuiNavInput_ ImGuiNavInput_KeyUp_ = new ImGuiNavInput_("ImGuiNavInput_KeyUp_");
  public final static ImGuiNavInput_ ImGuiNavInput_KeyDown_ = new ImGuiNavInput_("ImGuiNavInput_KeyDown_");
  public final static ImGuiNavInput_ ImGuiNavInput_COUNT = new ImGuiNavInput_("ImGuiNavInput_COUNT");
  public final static ImGuiNavInput_ ImGuiNavInput_InternalStart_ = new ImGuiNavInput_("ImGuiNavInput_InternalStart_", jimguiJNI.ImGuiNavInput_InternalStart__get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiNavInput_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiNavInput_.class + " with value " + swigValue);
  }

  private ImGuiNavInput_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiNavInput_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiNavInput_(String swigName, ImGuiNavInput_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiNavInput_[] swigValues = { ImGuiNavInput_Activate, ImGuiNavInput_Cancel, ImGuiNavInput_Input, ImGuiNavInput_Menu, ImGuiNavInput_DpadLeft, ImGuiNavInput_DpadRight, ImGuiNavInput_DpadUp, ImGuiNavInput_DpadDown, ImGuiNavInput_LStickLeft, ImGuiNavInput_LStickRight, ImGuiNavInput_LStickUp, ImGuiNavInput_LStickDown, ImGuiNavInput_FocusPrev, ImGuiNavInput_FocusNext, ImGuiNavInput_TweakSlow, ImGuiNavInput_TweakFast, ImGuiNavInput_KeyMenu_, ImGuiNavInput_KeyLeft_, ImGuiNavInput_KeyRight_, ImGuiNavInput_KeyUp_, ImGuiNavInput_KeyDown_, ImGuiNavInput_COUNT, ImGuiNavInput_InternalStart_ };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

