/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiColorEditFlags_ {
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_None = new ImGuiColorEditFlags_("ImGuiColorEditFlags_None", jimguiJNI.ImGuiColorEditFlags_None_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoAlpha = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoAlpha", jimguiJNI.ImGuiColorEditFlags_NoAlpha_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoPicker = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoPicker", jimguiJNI.ImGuiColorEditFlags_NoPicker_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoOptions = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoOptions", jimguiJNI.ImGuiColorEditFlags_NoOptions_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoSmallPreview = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoSmallPreview", jimguiJNI.ImGuiColorEditFlags_NoSmallPreview_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoInputs = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoInputs", jimguiJNI.ImGuiColorEditFlags_NoInputs_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoTooltip = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoTooltip", jimguiJNI.ImGuiColorEditFlags_NoTooltip_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoLabel = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoLabel", jimguiJNI.ImGuiColorEditFlags_NoLabel_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoSidePreview = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoSidePreview", jimguiJNI.ImGuiColorEditFlags_NoSidePreview_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_NoDragDrop = new ImGuiColorEditFlags_("ImGuiColorEditFlags_NoDragDrop", jimguiJNI.ImGuiColorEditFlags_NoDragDrop_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_AlphaBar = new ImGuiColorEditFlags_("ImGuiColorEditFlags_AlphaBar", jimguiJNI.ImGuiColorEditFlags_AlphaBar_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_AlphaPreview = new ImGuiColorEditFlags_("ImGuiColorEditFlags_AlphaPreview", jimguiJNI.ImGuiColorEditFlags_AlphaPreview_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_AlphaPreviewHalf = new ImGuiColorEditFlags_("ImGuiColorEditFlags_AlphaPreviewHalf", jimguiJNI.ImGuiColorEditFlags_AlphaPreviewHalf_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_HDR = new ImGuiColorEditFlags_("ImGuiColorEditFlags_HDR", jimguiJNI.ImGuiColorEditFlags_HDR_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_RGB = new ImGuiColorEditFlags_("ImGuiColorEditFlags_RGB", jimguiJNI.ImGuiColorEditFlags_RGB_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_HSV = new ImGuiColorEditFlags_("ImGuiColorEditFlags_HSV", jimguiJNI.ImGuiColorEditFlags_HSV_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_HEX = new ImGuiColorEditFlags_("ImGuiColorEditFlags_HEX", jimguiJNI.ImGuiColorEditFlags_HEX_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_Uint8 = new ImGuiColorEditFlags_("ImGuiColorEditFlags_Uint8", jimguiJNI.ImGuiColorEditFlags_Uint8_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_Float = new ImGuiColorEditFlags_("ImGuiColorEditFlags_Float", jimguiJNI.ImGuiColorEditFlags_Float_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_PickerHueBar = new ImGuiColorEditFlags_("ImGuiColorEditFlags_PickerHueBar", jimguiJNI.ImGuiColorEditFlags_PickerHueBar_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags_PickerHueWheel = new ImGuiColorEditFlags_("ImGuiColorEditFlags_PickerHueWheel", jimguiJNI.ImGuiColorEditFlags_PickerHueWheel_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags__InputsMask = new ImGuiColorEditFlags_("ImGuiColorEditFlags__InputsMask", jimguiJNI.ImGuiColorEditFlags__InputsMask_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags__DataTypeMask = new ImGuiColorEditFlags_("ImGuiColorEditFlags__DataTypeMask", jimguiJNI.ImGuiColorEditFlags__DataTypeMask_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags__PickerMask = new ImGuiColorEditFlags_("ImGuiColorEditFlags__PickerMask", jimguiJNI.ImGuiColorEditFlags__PickerMask_get());
  public final static ImGuiColorEditFlags_ ImGuiColorEditFlags__OptionsDefault = new ImGuiColorEditFlags_("ImGuiColorEditFlags__OptionsDefault", jimguiJNI.ImGuiColorEditFlags__OptionsDefault_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiColorEditFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiColorEditFlags_.class + " with value " + swigValue);
  }

  private ImGuiColorEditFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiColorEditFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiColorEditFlags_(String swigName, ImGuiColorEditFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiColorEditFlags_[] swigValues = { ImGuiColorEditFlags_None, ImGuiColorEditFlags_NoAlpha, ImGuiColorEditFlags_NoPicker, ImGuiColorEditFlags_NoOptions, ImGuiColorEditFlags_NoSmallPreview, ImGuiColorEditFlags_NoInputs, ImGuiColorEditFlags_NoTooltip, ImGuiColorEditFlags_NoLabel, ImGuiColorEditFlags_NoSidePreview, ImGuiColorEditFlags_NoDragDrop, ImGuiColorEditFlags_AlphaBar, ImGuiColorEditFlags_AlphaPreview, ImGuiColorEditFlags_AlphaPreviewHalf, ImGuiColorEditFlags_HDR, ImGuiColorEditFlags_RGB, ImGuiColorEditFlags_HSV, ImGuiColorEditFlags_HEX, ImGuiColorEditFlags_Uint8, ImGuiColorEditFlags_Float, ImGuiColorEditFlags_PickerHueBar, ImGuiColorEditFlags_PickerHueWheel, ImGuiColorEditFlags__InputsMask, ImGuiColorEditFlags__DataTypeMask, ImGuiColorEditFlags__PickerMask, ImGuiColorEditFlags__OptionsDefault };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

