/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImGuiStyle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImGuiStyle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImGuiStyle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImGuiStyle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setAlpha(float value) {
    jimguiJNI.ImGuiStyle_Alpha_set(swigCPtr, this, value);
  }

  public float getAlpha() {
    return jimguiJNI.ImGuiStyle_Alpha_get(swigCPtr, this);
  }

  public void setWindowPadding(ImVec2 value) {
    jimguiJNI.ImGuiStyle_WindowPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWindowPadding() {
    long cPtr = jimguiJNI.ImGuiStyle_WindowPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWindowRounding(float value) {
    jimguiJNI.ImGuiStyle_WindowRounding_set(swigCPtr, this, value);
  }

  public float getWindowRounding() {
    return jimguiJNI.ImGuiStyle_WindowRounding_get(swigCPtr, this);
  }

  public void setWindowBorderSize(float value) {
    jimguiJNI.ImGuiStyle_WindowBorderSize_set(swigCPtr, this, value);
  }

  public float getWindowBorderSize() {
    return jimguiJNI.ImGuiStyle_WindowBorderSize_get(swigCPtr, this);
  }

  public void setWindowMinSize(ImVec2 value) {
    jimguiJNI.ImGuiStyle_WindowMinSize_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWindowMinSize() {
    long cPtr = jimguiJNI.ImGuiStyle_WindowMinSize_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setWindowTitleAlign(ImVec2 value) {
    jimguiJNI.ImGuiStyle_WindowTitleAlign_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getWindowTitleAlign() {
    long cPtr = jimguiJNI.ImGuiStyle_WindowTitleAlign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setChildRounding(float value) {
    jimguiJNI.ImGuiStyle_ChildRounding_set(swigCPtr, this, value);
  }

  public float getChildRounding() {
    return jimguiJNI.ImGuiStyle_ChildRounding_get(swigCPtr, this);
  }

  public void setChildBorderSize(float value) {
    jimguiJNI.ImGuiStyle_ChildBorderSize_set(swigCPtr, this, value);
  }

  public float getChildBorderSize() {
    return jimguiJNI.ImGuiStyle_ChildBorderSize_get(swigCPtr, this);
  }

  public void setPopupRounding(float value) {
    jimguiJNI.ImGuiStyle_PopupRounding_set(swigCPtr, this, value);
  }

  public float getPopupRounding() {
    return jimguiJNI.ImGuiStyle_PopupRounding_get(swigCPtr, this);
  }

  public void setPopupBorderSize(float value) {
    jimguiJNI.ImGuiStyle_PopupBorderSize_set(swigCPtr, this, value);
  }

  public float getPopupBorderSize() {
    return jimguiJNI.ImGuiStyle_PopupBorderSize_get(swigCPtr, this);
  }

  public void setFramePadding(ImVec2 value) {
    jimguiJNI.ImGuiStyle_FramePadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getFramePadding() {
    long cPtr = jimguiJNI.ImGuiStyle_FramePadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setFrameRounding(float value) {
    jimguiJNI.ImGuiStyle_FrameRounding_set(swigCPtr, this, value);
  }

  public float getFrameRounding() {
    return jimguiJNI.ImGuiStyle_FrameRounding_get(swigCPtr, this);
  }

  public void setFrameBorderSize(float value) {
    jimguiJNI.ImGuiStyle_FrameBorderSize_set(swigCPtr, this, value);
  }

  public float getFrameBorderSize() {
    return jimguiJNI.ImGuiStyle_FrameBorderSize_get(swigCPtr, this);
  }

  public void setItemSpacing(ImVec2 value) {
    jimguiJNI.ImGuiStyle_ItemSpacing_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getItemSpacing() {
    long cPtr = jimguiJNI.ImGuiStyle_ItemSpacing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setItemInnerSpacing(ImVec2 value) {
    jimguiJNI.ImGuiStyle_ItemInnerSpacing_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getItemInnerSpacing() {
    long cPtr = jimguiJNI.ImGuiStyle_ItemInnerSpacing_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setTouchExtraPadding(ImVec2 value) {
    jimguiJNI.ImGuiStyle_TouchExtraPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getTouchExtraPadding() {
    long cPtr = jimguiJNI.ImGuiStyle_TouchExtraPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setIndentSpacing(float value) {
    jimguiJNI.ImGuiStyle_IndentSpacing_set(swigCPtr, this, value);
  }

  public float getIndentSpacing() {
    return jimguiJNI.ImGuiStyle_IndentSpacing_get(swigCPtr, this);
  }

  public void setColumnsMinSpacing(float value) {
    jimguiJNI.ImGuiStyle_ColumnsMinSpacing_set(swigCPtr, this, value);
  }

  public float getColumnsMinSpacing() {
    return jimguiJNI.ImGuiStyle_ColumnsMinSpacing_get(swigCPtr, this);
  }

  public void setScrollbarSize(float value) {
    jimguiJNI.ImGuiStyle_ScrollbarSize_set(swigCPtr, this, value);
  }

  public float getScrollbarSize() {
    return jimguiJNI.ImGuiStyle_ScrollbarSize_get(swigCPtr, this);
  }

  public void setScrollbarRounding(float value) {
    jimguiJNI.ImGuiStyle_ScrollbarRounding_set(swigCPtr, this, value);
  }

  public float getScrollbarRounding() {
    return jimguiJNI.ImGuiStyle_ScrollbarRounding_get(swigCPtr, this);
  }

  public void setGrabMinSize(float value) {
    jimguiJNI.ImGuiStyle_GrabMinSize_set(swigCPtr, this, value);
  }

  public float getGrabMinSize() {
    return jimguiJNI.ImGuiStyle_GrabMinSize_get(swigCPtr, this);
  }

  public void setGrabRounding(float value) {
    jimguiJNI.ImGuiStyle_GrabRounding_set(swigCPtr, this, value);
  }

  public float getGrabRounding() {
    return jimguiJNI.ImGuiStyle_GrabRounding_get(swigCPtr, this);
  }

  public void setButtonTextAlign(ImVec2 value) {
    jimguiJNI.ImGuiStyle_ButtonTextAlign_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getButtonTextAlign() {
    long cPtr = jimguiJNI.ImGuiStyle_ButtonTextAlign_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDisplayWindowPadding(ImVec2 value) {
    jimguiJNI.ImGuiStyle_DisplayWindowPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplayWindowPadding() {
    long cPtr = jimguiJNI.ImGuiStyle_DisplayWindowPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setDisplaySafeAreaPadding(ImVec2 value) {
    jimguiJNI.ImGuiStyle_DisplaySafeAreaPadding_set(swigCPtr, this, ImVec2.getCPtr(value), value);
  }

  public ImVec2 getDisplaySafeAreaPadding() {
    long cPtr = jimguiJNI.ImGuiStyle_DisplaySafeAreaPadding_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec2(cPtr, false);
  }

  public void setMouseCursorScale(float value) {
    jimguiJNI.ImGuiStyle_MouseCursorScale_set(swigCPtr, this, value);
  }

  public float getMouseCursorScale() {
    return jimguiJNI.ImGuiStyle_MouseCursorScale_get(swigCPtr, this);
  }

  public void setAntiAliasedLines(boolean value) {
    jimguiJNI.ImGuiStyle_AntiAliasedLines_set(swigCPtr, this, value);
  }

  public boolean getAntiAliasedLines() {
    return jimguiJNI.ImGuiStyle_AntiAliasedLines_get(swigCPtr, this);
  }

  public void setAntiAliasedFill(boolean value) {
    jimguiJNI.ImGuiStyle_AntiAliasedFill_set(swigCPtr, this, value);
  }

  public boolean getAntiAliasedFill() {
    return jimguiJNI.ImGuiStyle_AntiAliasedFill_get(swigCPtr, this);
  }

  public void setCurveTessellationTol(float value) {
    jimguiJNI.ImGuiStyle_CurveTessellationTol_set(swigCPtr, this, value);
  }

  public float getCurveTessellationTol() {
    return jimguiJNI.ImGuiStyle_CurveTessellationTol_get(swigCPtr, this);
  }

  public void setColors(ImVec4 value) {
    jimguiJNI.ImGuiStyle_Colors_set(swigCPtr, this, ImVec4.getCPtr(value), value);
  }

  public ImVec4 getColors() {
    long cPtr = jimguiJNI.ImGuiStyle_Colors_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ImVec4(cPtr, false);
  }

  public ImGuiStyle() {
    this(jimguiJNI.new_ImGuiStyle(), true);
  }

  public void ScaleAllSizes(float scale_factor) {
    jimguiJNI.ImGuiStyle_ScaleAllSizes(swigCPtr, this, scale_factor);
  }

}
