/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImGuiStorage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImGuiStorage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImGuiStorage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImGuiStorage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class Pair {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected Pair(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(Pair obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          jimguiJNI.delete_ImGuiStorage_Pair(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public void setKey(long value) {
      jimguiJNI.ImGuiStorage_Pair_key_set(swigCPtr, this, value);
    }
  
    public long getKey() {
      return jimguiJNI.ImGuiStorage_Pair_key_get(swigCPtr, this);
    }
  
    public void setVal_i(int value) {
      jimguiJNI.ImGuiStorage_Pair_val_i_set(swigCPtr, this, value);
    }
  
    public int getVal_i() {
      return jimguiJNI.ImGuiStorage_Pair_val_i_get(swigCPtr, this);
    }
  
    public void setVal_f(float value) {
      jimguiJNI.ImGuiStorage_Pair_val_f_set(swigCPtr, this, value);
    }
  
    public float getVal_f() {
      return jimguiJNI.ImGuiStorage_Pair_val_f_get(swigCPtr, this);
    }
  
    public void setVal_p(SWIGTYPE_p_void value) {
      jimguiJNI.ImGuiStorage_Pair_val_p_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
    }
  
    public SWIGTYPE_p_void getVal_p() {
      long cPtr = jimguiJNI.ImGuiStorage_Pair_val_p_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
    }
  
    public Pair(long _key, int _val_i) {
      this(jimguiJNI.new_ImGuiStorage_Pair__SWIG_0(_key, _val_i), true);
    }
  
    public Pair(long _key, float _val_f) {
      this(jimguiJNI.new_ImGuiStorage_Pair__SWIG_1(_key, _val_f), true);
    }
  
    public Pair(long _key, SWIGTYPE_p_void _val_p) {
      this(jimguiJNI.new_ImGuiStorage_Pair__SWIG_2(_key, SWIGTYPE_p_void.getCPtr(_val_p)), true);
    }
  
  }

  public void setData(SWIGTYPE_p_ImVectorT_ImGuiStorage__Pair_t value) {
    jimguiJNI.ImGuiStorage_Data_set(swigCPtr, this, SWIGTYPE_p_ImVectorT_ImGuiStorage__Pair_t.getCPtr(value));
  }

  public SWIGTYPE_p_ImVectorT_ImGuiStorage__Pair_t getData() {
    long cPtr = jimguiJNI.ImGuiStorage_Data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ImVectorT_ImGuiStorage__Pair_t(cPtr, false);
  }

  public void Clear() {
    jimguiJNI.ImGuiStorage_Clear(swigCPtr, this);
  }

  public int GetInt(long key, int default_val) {
    return jimguiJNI.ImGuiStorage_GetInt__SWIG_0(swigCPtr, this, key, default_val);
  }

  public int GetInt(long key) {
    return jimguiJNI.ImGuiStorage_GetInt__SWIG_1(swigCPtr, this, key);
  }

  public void SetInt(long key, int val) {
    jimguiJNI.ImGuiStorage_SetInt(swigCPtr, this, key, val);
  }

  public boolean GetBool(long key, boolean default_val) {
    return jimguiJNI.ImGuiStorage_GetBool__SWIG_0(swigCPtr, this, key, default_val);
  }

  public boolean GetBool(long key) {
    return jimguiJNI.ImGuiStorage_GetBool__SWIG_1(swigCPtr, this, key);
  }

  public void SetBool(long key, boolean val) {
    jimguiJNI.ImGuiStorage_SetBool(swigCPtr, this, key, val);
  }

  public float GetFloat(long key, float default_val) {
    return jimguiJNI.ImGuiStorage_GetFloat__SWIG_0(swigCPtr, this, key, default_val);
  }

  public float GetFloat(long key) {
    return jimguiJNI.ImGuiStorage_GetFloat__SWIG_1(swigCPtr, this, key);
  }

  public void SetFloat(long key, float val) {
    jimguiJNI.ImGuiStorage_SetFloat(swigCPtr, this, key, val);
  }

  public SWIGTYPE_p_void GetVoidPtr(long key) {
    long cPtr = jimguiJNI.ImGuiStorage_GetVoidPtr(swigCPtr, this, key);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void SetVoidPtr(long key, SWIGTYPE_p_void val) {
    jimguiJNI.ImGuiStorage_SetVoidPtr(swigCPtr, this, key, SWIGTYPE_p_void.getCPtr(val));
  }

  public SWIGTYPE_p_int GetIntRef(long key, int default_val) {
    long cPtr = jimguiJNI.ImGuiStorage_GetIntRef__SWIG_0(swigCPtr, this, key, default_val);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public SWIGTYPE_p_int GetIntRef(long key) {
    long cPtr = jimguiJNI.ImGuiStorage_GetIntRef__SWIG_1(swigCPtr, this, key);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public SWIGTYPE_p_bool GetBoolRef(long key, boolean default_val) {
    long cPtr = jimguiJNI.ImGuiStorage_GetBoolRef__SWIG_0(swigCPtr, this, key, default_val);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public SWIGTYPE_p_bool GetBoolRef(long key) {
    long cPtr = jimguiJNI.ImGuiStorage_GetBoolRef__SWIG_1(swigCPtr, this, key);
    return (cPtr == 0) ? null : new SWIGTYPE_p_bool(cPtr, false);
  }

  public SWIGTYPE_p_float GetFloatRef(long key, float default_val) {
    long cPtr = jimguiJNI.ImGuiStorage_GetFloatRef__SWIG_0(swigCPtr, this, key, default_val);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public SWIGTYPE_p_float GetFloatRef(long key) {
    long cPtr = jimguiJNI.ImGuiStorage_GetFloatRef__SWIG_1(swigCPtr, this, key);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public SWIGTYPE_p_p_void GetVoidPtrRef(long key, SWIGTYPE_p_void default_val) {
    long cPtr = jimguiJNI.ImGuiStorage_GetVoidPtrRef__SWIG_0(swigCPtr, this, key, SWIGTYPE_p_void.getCPtr(default_val));
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public SWIGTYPE_p_p_void GetVoidPtrRef(long key) {
    long cPtr = jimguiJNI.ImGuiStorage_GetVoidPtrRef__SWIG_1(swigCPtr, this, key);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_void(cPtr, false);
  }

  public void SetAllInt(int val) {
    jimguiJNI.ImGuiStorage_SetAllInt(swigCPtr, this, val);
  }

  public void BuildSortByKey() {
    jimguiJNI.ImGuiStorage_BuildSortByKey(swigCPtr, this);
  }

  public ImGuiStorage() {
    this(jimguiJNI.new_ImGuiStorage(), true);
  }

}
