/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiInputTextFlags_ {
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_None = new ImGuiInputTextFlags_("ImGuiInputTextFlags_None", jimguiJNI.ImGuiInputTextFlags_None_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CharsDecimal = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CharsDecimal", jimguiJNI.ImGuiInputTextFlags_CharsDecimal_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CharsHexadecimal = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CharsHexadecimal", jimguiJNI.ImGuiInputTextFlags_CharsHexadecimal_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CharsUppercase = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CharsUppercase", jimguiJNI.ImGuiInputTextFlags_CharsUppercase_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CharsNoBlank = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CharsNoBlank", jimguiJNI.ImGuiInputTextFlags_CharsNoBlank_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_AutoSelectAll = new ImGuiInputTextFlags_("ImGuiInputTextFlags_AutoSelectAll", jimguiJNI.ImGuiInputTextFlags_AutoSelectAll_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_EnterReturnsTrue = new ImGuiInputTextFlags_("ImGuiInputTextFlags_EnterReturnsTrue", jimguiJNI.ImGuiInputTextFlags_EnterReturnsTrue_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CallbackCompletion = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CallbackCompletion", jimguiJNI.ImGuiInputTextFlags_CallbackCompletion_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CallbackHistory = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CallbackHistory", jimguiJNI.ImGuiInputTextFlags_CallbackHistory_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CallbackAlways = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CallbackAlways", jimguiJNI.ImGuiInputTextFlags_CallbackAlways_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CallbackCharFilter = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CallbackCharFilter", jimguiJNI.ImGuiInputTextFlags_CallbackCharFilter_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_AllowTabInput = new ImGuiInputTextFlags_("ImGuiInputTextFlags_AllowTabInput", jimguiJNI.ImGuiInputTextFlags_AllowTabInput_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CtrlEnterForNewLine = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CtrlEnterForNewLine", jimguiJNI.ImGuiInputTextFlags_CtrlEnterForNewLine_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_NoHorizontalScroll = new ImGuiInputTextFlags_("ImGuiInputTextFlags_NoHorizontalScroll", jimguiJNI.ImGuiInputTextFlags_NoHorizontalScroll_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_AlwaysInsertMode = new ImGuiInputTextFlags_("ImGuiInputTextFlags_AlwaysInsertMode", jimguiJNI.ImGuiInputTextFlags_AlwaysInsertMode_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_ReadOnly = new ImGuiInputTextFlags_("ImGuiInputTextFlags_ReadOnly", jimguiJNI.ImGuiInputTextFlags_ReadOnly_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_Password = new ImGuiInputTextFlags_("ImGuiInputTextFlags_Password", jimguiJNI.ImGuiInputTextFlags_Password_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_NoUndoRedo = new ImGuiInputTextFlags_("ImGuiInputTextFlags_NoUndoRedo", jimguiJNI.ImGuiInputTextFlags_NoUndoRedo_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_CharsScientific = new ImGuiInputTextFlags_("ImGuiInputTextFlags_CharsScientific", jimguiJNI.ImGuiInputTextFlags_CharsScientific_get());
  public final static ImGuiInputTextFlags_ ImGuiInputTextFlags_Multiline = new ImGuiInputTextFlags_("ImGuiInputTextFlags_Multiline", jimguiJNI.ImGuiInputTextFlags_Multiline_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiInputTextFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiInputTextFlags_.class + " with value " + swigValue);
  }

  private ImGuiInputTextFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiInputTextFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiInputTextFlags_(String swigName, ImGuiInputTextFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiInputTextFlags_[] swigValues = { ImGuiInputTextFlags_None, ImGuiInputTextFlags_CharsDecimal, ImGuiInputTextFlags_CharsHexadecimal, ImGuiInputTextFlags_CharsUppercase, ImGuiInputTextFlags_CharsNoBlank, ImGuiInputTextFlags_AutoSelectAll, ImGuiInputTextFlags_EnterReturnsTrue, ImGuiInputTextFlags_CallbackCompletion, ImGuiInputTextFlags_CallbackHistory, ImGuiInputTextFlags_CallbackAlways, ImGuiInputTextFlags_CallbackCharFilter, ImGuiInputTextFlags_AllowTabInput, ImGuiInputTextFlags_CtrlEnterForNewLine, ImGuiInputTextFlags_NoHorizontalScroll, ImGuiInputTextFlags_AlwaysInsertMode, ImGuiInputTextFlags_ReadOnly, ImGuiInputTextFlags_Password, ImGuiInputTextFlags_NoUndoRedo, ImGuiInputTextFlags_CharsScientific, ImGuiInputTextFlags_Multiline };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

