/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public final class ImGuiComboFlags_ {
  public final static ImGuiComboFlags_ ImGuiComboFlags_None = new ImGuiComboFlags_("ImGuiComboFlags_None", jimguiJNI.ImGuiComboFlags_None_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_PopupAlignLeft = new ImGuiComboFlags_("ImGuiComboFlags_PopupAlignLeft", jimguiJNI.ImGuiComboFlags_PopupAlignLeft_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_HeightSmall = new ImGuiComboFlags_("ImGuiComboFlags_HeightSmall", jimguiJNI.ImGuiComboFlags_HeightSmall_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_HeightRegular = new ImGuiComboFlags_("ImGuiComboFlags_HeightRegular", jimguiJNI.ImGuiComboFlags_HeightRegular_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_HeightLarge = new ImGuiComboFlags_("ImGuiComboFlags_HeightLarge", jimguiJNI.ImGuiComboFlags_HeightLarge_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_HeightLargest = new ImGuiComboFlags_("ImGuiComboFlags_HeightLargest", jimguiJNI.ImGuiComboFlags_HeightLargest_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_NoArrowButton = new ImGuiComboFlags_("ImGuiComboFlags_NoArrowButton", jimguiJNI.ImGuiComboFlags_NoArrowButton_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_NoPreview = new ImGuiComboFlags_("ImGuiComboFlags_NoPreview", jimguiJNI.ImGuiComboFlags_NoPreview_get());
  public final static ImGuiComboFlags_ ImGuiComboFlags_HeightMask_ = new ImGuiComboFlags_("ImGuiComboFlags_HeightMask_", jimguiJNI.ImGuiComboFlags_HeightMask__get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImGuiComboFlags_ swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImGuiComboFlags_.class + " with value " + swigValue);
  }

  private ImGuiComboFlags_(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImGuiComboFlags_(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImGuiComboFlags_(String swigName, ImGuiComboFlags_ swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImGuiComboFlags_[] swigValues = { ImGuiComboFlags_None, ImGuiComboFlags_PopupAlignLeft, ImGuiComboFlags_HeightSmall, ImGuiComboFlags_HeightRegular, ImGuiComboFlags_HeightLarge, ImGuiComboFlags_HeightLargest, ImGuiComboFlags_NoArrowButton, ImGuiComboFlags_NoPreview, ImGuiComboFlags_HeightMask_ };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

