/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImVec4 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImVec4(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImVec4 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImVec4(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    jimguiJNI.ImVec4_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return jimguiJNI.ImVec4_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    jimguiJNI.ImVec4_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return jimguiJNI.ImVec4_y_get(swigCPtr, this);
  }

  public void setZ(float value) {
    jimguiJNI.ImVec4_z_set(swigCPtr, this, value);
  }

  public float getZ() {
    return jimguiJNI.ImVec4_z_get(swigCPtr, this);
  }

  public void setW(float value) {
    jimguiJNI.ImVec4_w_set(swigCPtr, this, value);
  }

  public float getW() {
    return jimguiJNI.ImVec4_w_get(swigCPtr, this);
  }

  public ImVec4() {
    this(jimguiJNI.new_ImVec4__SWIG_0(), true);
  }

  public ImVec4(float _x, float _y, float _z, float _w) {
    this(jimguiJNI.new_ImVec4__SWIG_1(_x, _y, _z, _w), true);
  }

}
