/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class ImVec2 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ImVec2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImVec2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_ImVec2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    jimguiJNI.ImVec2_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return jimguiJNI.ImVec2_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    jimguiJNI.ImVec2_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return jimguiJNI.ImVec2_y_get(swigCPtr, this);
  }

  public ImVec2() {
    this(jimguiJNI.new_ImVec2__SWIG_0(), true);
  }

  public ImVec2(float _x, float _y) {
    this(jimguiJNI.new_ImVec2__SWIG_1(_x, _y), true);
  }

}
