/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public interface jimguiConstants {
  public final static String IMGUI_VERSION = jimguiJNI.IMGUI_VERSION_get();
  public final static String IMGUI_PAYLOAD_TYPE_COLOR_3F = jimguiJNI.IMGUI_PAYLOAD_TYPE_COLOR_3F_get();
  public final static String IMGUI_PAYLOAD_TYPE_COLOR_4F = jimguiJNI.IMGUI_PAYLOAD_TYPE_COLOR_4F_get();
  public final static int IM_COL32_R_SHIFT = jimguiJNI.IM_COL32_R_SHIFT_get();
  public final static int IM_COL32_G_SHIFT = jimguiJNI.IM_COL32_G_SHIFT_get();
  public final static int IM_COL32_B_SHIFT = jimguiJNI.IM_COL32_B_SHIFT_get();
  public final static int IM_COL32_A_SHIFT = jimguiJNI.IM_COL32_A_SHIFT_get();
  public final static int IM_COL32_A_MASK = jimguiJNI.IM_COL32_A_MASK_get();
}
