/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class sub_window_info {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected sub_window_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(sub_window_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jimguiJNI.delete_sub_window_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(float value) {
    jimguiJNI.sub_window_info_x_set(swigCPtr, this, value);
  }

  public float getX() {
    return jimguiJNI.sub_window_info_x_get(swigCPtr, this);
  }

  public void setY(float value) {
    jimguiJNI.sub_window_info_y_set(swigCPtr, this, value);
  }

  public float getY() {
    return jimguiJNI.sub_window_info_y_get(swigCPtr, this);
  }

  public void setMargin_right(int value) {
    jimguiJNI.sub_window_info_margin_right_set(swigCPtr, this, value);
  }

  public int getMargin_right() {
    return jimguiJNI.sub_window_info_margin_right_get(swigCPtr, this);
  }

  public void setMargin_bottom(int value) {
    jimguiJNI.sub_window_info_margin_bottom_set(swigCPtr, this, value);
  }

  public int getMargin_bottom() {
    return jimguiJNI.sub_window_info_margin_bottom_get(swigCPtr, this);
  }

  public sub_window_info() {
    this(jimguiJNI.new_sub_window_info(), true);
  }

}
