/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.knziha.jimgui;

public class SWIGTYPE_p_f_p_void_int_p_p_q_const__char__bool {
  private transient long swigCPtr;

  protected SWIGTYPE_p_f_p_void_int_p_p_q_const__char__bool(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_f_p_void_int_p_p_q_const__char__bool() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_f_p_void_int_p_p_q_const__char__bool obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

